package Index;

import Keluarga.Keluarga_RT01;
import Warga.Menu_RT01;
import Bantuan.Bantuan_RT01;
import Warga.Menu_RT02;
import Warga.Menu_RT03;
import Warga.Menu_RT04;
import Keluarga.Keluarga_RT02;
import Keluarga.Keluarga_RT03;
import Keluarga.Keluarga_RT04;
import Bantuan.Bantuan_RT02;
import Bantuan.Bantuan_RT03;
import Bantuan.Bantuan_RT04;
import Laporan.Laporan_RT01;
import Laporan.Laporan_RT02;
import Laporan.Laporan_RT03;
import Laporan.Laporan_RT04;
import java.io.File;
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
       ButtonRT01_Kelompok2.setEnabled(false);
                    ButtonRT02_Kelompok2.setEnabled(false);
                    ButtonRT03_Kelompok2.setEnabled(false);
                    ButtonRT04_Kelompok2.setEnabled(false);
                    ButtonKKRT01_Kelompok2.setEnabled(false);
                    ButtonKKRT02_Kelompok2.setEnabled(false);
                    ButtonKKRT03_Kelompok2.setEnabled(false);
                    ButtonKKRT04_Kelompok2.setEnabled(false);
                    ButtonBRT01_Kelompok2.setEnabled(false);
                    ButtonBRT02_Kelompok2.setEnabled(false);
                    ButtonBRT03_Kelompok2.setEnabled(false);
                    ButtonBRT04_Kelompok2.setEnabled(false);
                    ButtonLRT01_Kelompok2.setEnabled(false);
                    ButtonLRT02_Kelompok2.setEnabled(false);
                    ButtonLRT03_Kelompok2.setEnabled(false);
                    ButtonLRT04_Kelompok2.setEnabled(false);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogLogin_Kelompok2 = new javax.swing.JDialog();
        PanelUtama_Kelompok2 = new javax.swing.JPanel();
        PanelMenu_Kelompok3 = new javax.swing.JPanel();
        LabelJudul1_Kelompok3 = new javax.swing.JLabel();
        LabelJudul2_Kelompok2 = new javax.swing.JLabel();
        LabelJudul3_Kelompok2 = new javax.swing.JLabel();
        LabelJudul4_Kelompok2 = new javax.swing.JLabel();
        LabelNama_Kelompok2 = new javax.swing.JLabel();
        LabelPIN_Kelompok2 = new javax.swing.JLabel();
        LabelRT_Kelompok2 = new javax.swing.JLabel();
        TextFieldNama_Kelompok2 = new javax.swing.JTextField();
        PasswordFieldPIN_Kelompok2 = new javax.swing.JPasswordField();
        ComboBoxRT_Kelompok2 = new javax.swing.JComboBox<>();
        ButtonLogin_Kelompok3 = new javax.swing.JButton();
        ButtonBatal_Kelompok2 = new javax.swing.JButton();
        PanelHeader_Kelompok2 = new javax.swing.JPanel();
        LabelLogo1_Kelompok2 = new javax.swing.JLabel();
        LabelLogo2_Kelompok2 = new javax.swing.JLabel();
        LabelJudul1 = new javax.swing.JLabel();
        PanelMenu_Kelompok2 = new javax.swing.JPanel();
        ButtonKKRT01_Kelompok2 = new javax.swing.JButton();
        ButtonKKRT02_Kelompok2 = new javax.swing.JButton();
        ButtonKKRT03_Kelompok2 = new javax.swing.JButton();
        ButtonKKRT04_Kelompok2 = new javax.swing.JButton();
        PanelGaris1_Kelompok2 = new javax.swing.JPanel();
        ButtonRT01_Kelompok2 = new javax.swing.JButton();
        ButtonRT02_Kelompok2 = new javax.swing.JButton();
        ButtonRT03_Kelompok2 = new javax.swing.JButton();
        ButtonRT04_Kelompok2 = new javax.swing.JButton();
        PanelGaris2_Kelompok2 = new javax.swing.JPanel();
        PanelGaris3_Kelompok2 = new javax.swing.JPanel();
        ButtonBRT01_Kelompok2 = new javax.swing.JButton();
        ButtonBRT02_Kelompok2 = new javax.swing.JButton();
        ButtonBRT03_Kelompok2 = new javax.swing.JButton();
        ButtonBRT04_Kelompok2 = new javax.swing.JButton();
        ButtonLRT01_Kelompok2 = new javax.swing.JButton();
        ButtonLRT04_Kelompok2 = new javax.swing.JButton();
        ButtonLRT02_Kelompok2 = new javax.swing.JButton();
        ButtonLRT03_Kelompok2 = new javax.swing.JButton();
        DesktopPane_Kelompok2 = new javax.swing.JDesktopPane();
        PanelHeader2_Kelompok2 = new javax.swing.JPanel();
        ButtonKeluar_Kelompok2 = new javax.swing.JButton();
        ButtonSO_Kelompok2 = new javax.swing.JButton();
        ButtonDev_Kelompok3 = new javax.swing.JButton();
        ButtonBantuan_Kelompok3 = new javax.swing.JButton();
        ButtonLogin_Kelompok2 = new javax.swing.JButton();

        DialogLogin_Kelompok2.setLocation(new java.awt.Point(250, 120));
        DialogLogin_Kelompok2.setMinimumSize(new java.awt.Dimension(822, 388));

        PanelUtama_Kelompok2.setBackground(new java.awt.Color(153, 153, 153));

        PanelMenu_Kelompok3.setBackground(new java.awt.Color(0, 102, 102));

        LabelJudul1_Kelompok3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelJudul1_Kelompok3.setForeground(new java.awt.Color(255, 255, 255));
        LabelJudul1_Kelompok3.setText("LOGIN USER");

        LabelJudul2_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/team.png"))); // NOI18N

        LabelJudul3_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelJudul3_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        LabelJudul3_Kelompok2.setText("Aplikasi Pendataan Desa Sekekuda RW 07");

        javax.swing.GroupLayout PanelMenu_Kelompok3Layout = new javax.swing.GroupLayout(PanelMenu_Kelompok3);
        PanelMenu_Kelompok3.setLayout(PanelMenu_Kelompok3Layout);
        PanelMenu_Kelompok3Layout.setHorizontalGroup(
            PanelMenu_Kelompok3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenu_Kelompok3Layout.createSequentialGroup()
                .addGroup(PanelMenu_Kelompok3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenu_Kelompok3Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(LabelJudul3_Kelompok2))
                    .addGroup(PanelMenu_Kelompok3Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(LabelJudul1_Kelompok3))
                    .addGroup(PanelMenu_Kelompok3Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(LabelJudul2_Kelompok2)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        PanelMenu_Kelompok3Layout.setVerticalGroup(
            PanelMenu_Kelompok3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenu_Kelompok3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelJudul2_Kelompok2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelJudul1_Kelompok3)
                .addGap(18, 18, 18)
                .addComponent(LabelJudul3_Kelompok2)
                .addGap(179, 179, 179))
        );

        LabelJudul4_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelJudul4_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        LabelJudul4_Kelompok2.setText("LOGIN");

        LabelNama_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelNama_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        LabelNama_Kelompok2.setText("Nama");

        LabelPIN_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelPIN_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        LabelPIN_Kelompok2.setText("PIN");

        LabelRT_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelRT_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        LabelRT_Kelompok2.setText("RT");

        ComboBoxRT_Kelompok2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "RT 01", "RT 02", "RT 03", "RT 04" }));

        ButtonLogin_Kelompok3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonLogin_Kelompok3.setText("Login");
        ButtonLogin_Kelompok3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogin_Kelompok3ActionPerformed(evt);
            }
        });

        ButtonBatal_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonBatal_Kelompok2.setText("Batal");
        ButtonBatal_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBatal_Kelompok2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelUtama_Kelompok2Layout = new javax.swing.GroupLayout(PanelUtama_Kelompok2);
        PanelUtama_Kelompok2.setLayout(PanelUtama_Kelompok2Layout);
        PanelUtama_Kelompok2Layout.setHorizontalGroup(
            PanelUtama_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUtama_Kelompok2Layout.createSequentialGroup()
                .addComponent(PanelMenu_Kelompok3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(PanelUtama_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUtama_Kelompok2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(LabelJudul4_Kelompok2))
                    .addGroup(PanelUtama_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(PanelUtama_Kelompok2Layout.createSequentialGroup()
                            .addComponent(ButtonLogin_Kelompok3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonBatal_Kelompok2))
                        .addGroup(PanelUtama_Kelompok2Layout.createSequentialGroup()
                            .addGroup(PanelUtama_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LabelNama_Kelompok2)
                                .addComponent(LabelPIN_Kelompok2)
                                .addComponent(LabelRT_Kelompok2))
                            .addGap(18, 18, 18)
                            .addGroup(PanelUtama_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PanelUtama_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextFieldNama_Kelompok2)
                                    .addComponent(PasswordFieldPIN_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(ComboBoxRT_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(55, 55, 55))
        );
        PanelUtama_Kelompok2Layout.setVerticalGroup(
            PanelUtama_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMenu_Kelompok3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelUtama_Kelompok2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(LabelJudul4_Kelompok2)
                .addGap(49, 49, 49)
                .addGroup(PanelUtama_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNama_Kelompok2)
                    .addComponent(TextFieldNama_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelUtama_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPIN_Kelompok2)
                    .addComponent(PasswordFieldPIN_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelUtama_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelRT_Kelompok2)
                    .addComponent(ComboBoxRT_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(PanelUtama_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonLogin_Kelompok3)
                    .addComponent(ButtonBatal_Kelompok2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DialogLogin_Kelompok2Layout = new javax.swing.GroupLayout(DialogLogin_Kelompok2.getContentPane());
        DialogLogin_Kelompok2.getContentPane().setLayout(DialogLogin_Kelompok2Layout);
        DialogLogin_Kelompok2Layout.setHorizontalGroup(
            DialogLogin_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUtama_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogLogin_Kelompok2Layout.setVerticalGroup(
            DialogLogin_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUtama_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(793, 652));

        PanelHeader_Kelompok2.setBackground(new java.awt.Color(0, 204, 204));

        LabelLogo1_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Screenshot_20220716-102029_1 - Copy.jpg"))); // NOI18N

        LabelLogo2_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Screenshot_20220716-102029_1 - Copy.jpg"))); // NOI18N

        LabelJudul1.setBackground(new java.awt.Color(0, 102, 102));
        LabelJudul1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelJudul1.setForeground(new java.awt.Color(255, 255, 255));
        LabelJudul1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelJudul1.setText("<html>\nDesa Sekekuda\n<br><center>RW07</center></br>\n</html> ");

        javax.swing.GroupLayout PanelHeader_Kelompok2Layout = new javax.swing.GroupLayout(PanelHeader_Kelompok2);
        PanelHeader_Kelompok2.setLayout(PanelHeader_Kelompok2Layout);
        PanelHeader_Kelompok2Layout.setHorizontalGroup(
            PanelHeader_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelJudul1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
            .addGroup(PanelHeader_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelHeader_Kelompok2Layout.createSequentialGroup()
                    .addComponent(LabelLogo1_Kelompok2)
                    .addGap(0, 351, Short.MAX_VALUE)))
            .addGroup(PanelHeader_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHeader_Kelompok2Layout.createSequentialGroup()
                    .addGap(0, 351, Short.MAX_VALUE)
                    .addComponent(LabelLogo2_Kelompok2)))
        );
        PanelHeader_Kelompok2Layout.setVerticalGroup(
            PanelHeader_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeader_Kelompok2Layout.createSequentialGroup()
                .addComponent(LabelJudul1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelHeader_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelHeader_Kelompok2Layout.createSequentialGroup()
                    .addComponent(LabelLogo1_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(PanelHeader_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelHeader_Kelompok2Layout.createSequentialGroup()
                    .addComponent(LabelLogo2_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        PanelMenu_Kelompok2.setBackground(new java.awt.Color(0, 102, 102));

        ButtonKKRT01_Kelompok2.setBackground(new java.awt.Color(0, 51, 51));
        ButtonKKRT01_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonKKRT01_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonKKRT01_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/family (1).png"))); // NOI18N
        ButtonKKRT01_Kelompok2.setText("KK RT-01");
        ButtonKKRT01_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKKRT01_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonKKRT02_Kelompok2.setBackground(new java.awt.Color(0, 51, 51));
        ButtonKKRT02_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonKKRT02_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonKKRT02_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/family (2).png"))); // NOI18N
        ButtonKKRT02_Kelompok2.setText("KK RT-02");
        ButtonKKRT02_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKKRT02_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonKKRT03_Kelompok2.setBackground(new java.awt.Color(0, 51, 51));
        ButtonKKRT03_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonKKRT03_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonKKRT03_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/family (3).png"))); // NOI18N
        ButtonKKRT03_Kelompok2.setText("KK RT-03");
        ButtonKKRT03_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKKRT03_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonKKRT04_Kelompok2.setBackground(new java.awt.Color(0, 51, 51));
        ButtonKKRT04_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonKKRT04_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonKKRT04_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/family.png"))); // NOI18N
        ButtonKKRT04_Kelompok2.setText("KK RT-04");
        ButtonKKRT04_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKKRT04_Kelompok2ActionPerformed(evt);
            }
        });

        PanelGaris1_Kelompok2.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout PanelGaris1_Kelompok2Layout = new javax.swing.GroupLayout(PanelGaris1_Kelompok2);
        PanelGaris1_Kelompok2.setLayout(PanelGaris1_Kelompok2Layout);
        PanelGaris1_Kelompok2Layout.setHorizontalGroup(
            PanelGaris1_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelGaris1_Kelompok2Layout.setVerticalGroup(
            PanelGaris1_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        ButtonRT01_Kelompok2.setBackground(new java.awt.Color(0, 51, 51));
        ButtonRT01_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonRT01_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonRT01_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/user.png"))); // NOI18N
        ButtonRT01_Kelompok2.setText("RT 01");
        ButtonRT01_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRT01_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonRT02_Kelompok2.setBackground(new java.awt.Color(0, 51, 51));
        ButtonRT02_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonRT02_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonRT02_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/user (1).png"))); // NOI18N
        ButtonRT02_Kelompok2.setText("RT 02");
        ButtonRT02_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRT02_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonRT03_Kelompok2.setBackground(new java.awt.Color(0, 51, 51));
        ButtonRT03_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonRT03_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonRT03_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/user (2).png"))); // NOI18N
        ButtonRT03_Kelompok2.setText("RT 03");
        ButtonRT03_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRT03_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonRT04_Kelompok2.setBackground(new java.awt.Color(0, 51, 51));
        ButtonRT04_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonRT04_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonRT04_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/user (3).png"))); // NOI18N
        ButtonRT04_Kelompok2.setText("RT 04");
        ButtonRT04_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRT04_Kelompok2ActionPerformed(evt);
            }
        });

        PanelGaris2_Kelompok2.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout PanelGaris2_Kelompok2Layout = new javax.swing.GroupLayout(PanelGaris2_Kelompok2);
        PanelGaris2_Kelompok2.setLayout(PanelGaris2_Kelompok2Layout);
        PanelGaris2_Kelompok2Layout.setHorizontalGroup(
            PanelGaris2_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelGaris2_Kelompok2Layout.setVerticalGroup(
            PanelGaris2_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        PanelGaris3_Kelompok2.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout PanelGaris3_Kelompok2Layout = new javax.swing.GroupLayout(PanelGaris3_Kelompok2);
        PanelGaris3_Kelompok2.setLayout(PanelGaris3_Kelompok2Layout);
        PanelGaris3_Kelompok2Layout.setHorizontalGroup(
            PanelGaris3_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelGaris3_Kelompok2Layout.setVerticalGroup(
            PanelGaris3_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        ButtonBRT01_Kelompok2.setBackground(new java.awt.Color(0, 51, 51));
        ButtonBRT01_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonBRT01_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonBRT01_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/checklist.png"))); // NOI18N
        ButtonBRT01_Kelompok2.setText("Bantuan RT-01");
        ButtonBRT01_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBRT01_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonBRT02_Kelompok2.setBackground(new java.awt.Color(0, 51, 51));
        ButtonBRT02_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonBRT02_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonBRT02_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/checklist (1).png"))); // NOI18N
        ButtonBRT02_Kelompok2.setText("Bantuan RT-02");
        ButtonBRT02_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBRT02_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonBRT03_Kelompok2.setBackground(new java.awt.Color(0, 51, 51));
        ButtonBRT03_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonBRT03_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonBRT03_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/checklist (2).png"))); // NOI18N
        ButtonBRT03_Kelompok2.setText("Bantuan RT-03");
        ButtonBRT03_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBRT03_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonBRT04_Kelompok2.setBackground(new java.awt.Color(0, 51, 51));
        ButtonBRT04_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonBRT04_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonBRT04_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/checklist (3).png"))); // NOI18N
        ButtonBRT04_Kelompok2.setText("Bantuan RT-04");
        ButtonBRT04_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBRT04_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonLRT01_Kelompok2.setBackground(new java.awt.Color(0, 51, 51));
        ButtonLRT01_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonLRT01_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLRT01_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/immigration.png"))); // NOI18N
        ButtonLRT01_Kelompok2.setText("Laporan RT-01");
        ButtonLRT01_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLRT01_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonLRT04_Kelompok2.setBackground(new java.awt.Color(0, 51, 51));
        ButtonLRT04_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonLRT04_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLRT04_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/immigration (3).png"))); // NOI18N
        ButtonLRT04_Kelompok2.setText("Laporan RT-04");
        ButtonLRT04_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLRT04_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonLRT02_Kelompok2.setBackground(new java.awt.Color(0, 51, 51));
        ButtonLRT02_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonLRT02_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLRT02_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/immigration (1).png"))); // NOI18N
        ButtonLRT02_Kelompok2.setText("Laporan RT-02");
        ButtonLRT02_Kelompok2.setToolTipText("");
        ButtonLRT02_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLRT02_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonLRT03_Kelompok2.setBackground(new java.awt.Color(0, 51, 51));
        ButtonLRT03_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonLRT03_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLRT03_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/immigration (2).png"))); // NOI18N
        ButtonLRT03_Kelompok2.setText("Laporan RT-03");
        ButtonLRT03_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLRT03_Kelompok2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMenu_Kelompok2Layout = new javax.swing.GroupLayout(PanelMenu_Kelompok2);
        PanelMenu_Kelompok2.setLayout(PanelMenu_Kelompok2Layout);
        PanelMenu_Kelompok2Layout.setHorizontalGroup(
            PanelMenu_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGaris1_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelGaris2_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelGaris3_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelMenu_Kelompok2Layout.createSequentialGroup()
                .addGroup(PanelMenu_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenu_Kelompok2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ButtonLRT02_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelMenu_Kelompok2Layout.createSequentialGroup()
                        .addGroup(PanelMenu_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelMenu_Kelompok2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ButtonLRT04_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelMenu_Kelompok2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(PanelMenu_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButtonKKRT01_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonKKRT02_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonKKRT03_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonKKRT04_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelMenu_Kelompok2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelMenu_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelMenu_Kelompok2Layout.createSequentialGroup()
                                .addGroup(PanelMenu_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButtonBRT01_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonBRT02_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonBRT03_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonBRT04_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenu_Kelompok2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(PanelMenu_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenu_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ButtonRT01_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ButtonRT02_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ButtonRT03_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ButtonRT04_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ButtonLRT01_Kelompok2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addGroup(PanelMenu_Kelompok2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonLRT03_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelMenu_Kelompok2Layout.setVerticalGroup(
            PanelMenu_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenu_Kelompok2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonRT01_Kelompok2)
                .addGap(7, 7, 7)
                .addComponent(ButtonRT02_Kelompok2)
                .addGap(7, 7, 7)
                .addComponent(ButtonRT03_Kelompok2)
                .addGap(7, 7, 7)
                .addComponent(ButtonRT04_Kelompok2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelGaris1_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonKKRT01_Kelompok2)
                .addGap(7, 7, 7)
                .addComponent(ButtonKKRT02_Kelompok2)
                .addGap(7, 7, 7)
                .addComponent(ButtonKKRT03_Kelompok2)
                .addGap(7, 7, 7)
                .addComponent(ButtonKKRT04_Kelompok2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelGaris2_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonBRT01_Kelompok2)
                .addGap(7, 7, 7)
                .addComponent(ButtonBRT02_Kelompok2)
                .addGap(7, 7, 7)
                .addComponent(ButtonBRT03_Kelompok2)
                .addGap(7, 7, 7)
                .addComponent(ButtonBRT04_Kelompok2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelGaris3_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonLRT01_Kelompok2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonLRT02_Kelompok2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonLRT03_Kelompok2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonLRT04_Kelompok2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        DesktopPane_Kelompok2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout DesktopPane_Kelompok2Layout = new javax.swing.GroupLayout(DesktopPane_Kelompok2);
        DesktopPane_Kelompok2.setLayout(DesktopPane_Kelompok2Layout);
        DesktopPane_Kelompok2Layout.setHorizontalGroup(
            DesktopPane_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );
        DesktopPane_Kelompok2Layout.setVerticalGroup(
            DesktopPane_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        PanelHeader2_Kelompok2.setBackground(new java.awt.Color(0, 153, 153));

        ButtonKeluar_Kelompok2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ButtonKeluar_Kelompok2.setText("KELUAR");
        ButtonKeluar_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKeluar_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonSO_Kelompok2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ButtonSO_Kelompok2.setText("STRUKTUR ORGANISASI");
        ButtonSO_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSO_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonDev_Kelompok3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ButtonDev_Kelompok3.setText("Developer");
        ButtonDev_Kelompok3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDev_Kelompok3ActionPerformed(evt);
            }
        });

        ButtonBantuan_Kelompok3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ButtonBantuan_Kelompok3.setText("Bantuan");
        ButtonBantuan_Kelompok3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBantuan_Kelompok3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelHeader2_Kelompok2Layout = new javax.swing.GroupLayout(PanelHeader2_Kelompok2);
        PanelHeader2_Kelompok2.setLayout(PanelHeader2_Kelompok2Layout);
        PanelHeader2_Kelompok2Layout.setHorizontalGroup(
            PanelHeader2_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHeader2_Kelompok2Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(ButtonSO_Kelompok2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonBantuan_Kelompok3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonDev_Kelompok3)
                .addGap(18, 18, 18)
                .addComponent(ButtonKeluar_Kelompok2))
        );
        PanelHeader2_Kelompok2Layout.setVerticalGroup(
            PanelHeader2_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHeader2_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(ButtonKeluar_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addComponent(ButtonSO_Kelompok2)
                .addComponent(ButtonDev_Kelompok3)
                .addComponent(ButtonBantuan_Kelompok3))
        );

        ButtonLogin_Kelompok2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ButtonLogin_Kelompok2.setText("LOGIN");
        ButtonLogin_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogin_Kelompok2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelHeader_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonLogin_Kelompok2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelHeader2_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelMenu_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DesktopPane_Kelompok2))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelHeader_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelHeader2_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonLogin_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DesktopPane_Kelompok2)
                        .addContainerGap())
                    .addComponent(PanelMenu_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(809, 710));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonKKRT01_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKKRT01_Kelompok2ActionPerformed
    Keluarga_RT01 KKRT01 = new Keluarga_RT01();
    DesktopPane_Kelompok2.add(KKRT01);
    KKRT01.setVisible(true);
    }//GEN-LAST:event_ButtonKKRT01_Kelompok2ActionPerformed

    private void ButtonLogin_Kelompok3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogin_Kelompok3ActionPerformed
        try{
            Connection Koneksi=DriverManager.getConnection("jdbc:mysql://localhost:3306/desa_sekekuda","root","");
            Statement stat= Koneksi.createStatement();
            ResultSet rs=stat.executeQuery("select * from login where Nama='"+TextFieldNama_Kelompok2.getText()+"'"
                + "and PIN='"+PasswordFieldPIN_Kelompok2.getText()
                +"'and Level='"+ComboBoxRT_Kelompok2.getSelectedItem()+"'" );
            rs.last();
            if(TextFieldNama_Kelompok2.getText().equals("dena") &&
                PasswordFieldPIN_Kelompok2.getText().equals("0012")&&
                ComboBoxRT_Kelompok2.getSelectedItem().equals("RT 01")){
                ButtonRT01_Kelompok2.setEnabled(true);
                ButtonRT02_Kelompok2.setEnabled(false);
                ButtonRT03_Kelompok2.setEnabled(false);
                ButtonRT04_Kelompok2.setEnabled(false);
                ButtonKKRT01_Kelompok2.setEnabled(true);
                ButtonKKRT02_Kelompok2.setEnabled(false);
                ButtonKKRT03_Kelompok2.setEnabled(false);
                ButtonKKRT04_Kelompok2.setEnabled(false);
                ButtonBRT01_Kelompok2.setEnabled(true);
                ButtonBRT02_Kelompok2.setEnabled(false);
                ButtonBRT03_Kelompok2.setEnabled(false);
                ButtonBRT04_Kelompok2.setEnabled(false);
                ButtonLRT01_Kelompok2.setEnabled(true);
                ButtonLRT02_Kelompok2.setEnabled(false);
                ButtonLRT03_Kelompok2.setEnabled(false);
                ButtonLRT04_Kelompok2.setEnabled(false);
                DialogLogin_Kelompok2.setVisible(false);
                TextFieldNama_Kelompok2.setText("");
                PasswordFieldPIN_Kelompok2.setText("");
                ComboBoxRT_Kelompok2.setSelectedItem("RT 01");
            }else if(rs.getRow()>=1){
                if(ComboBoxRT_Kelompok2.getSelectedItem().equals("RT 01")){
                    ButtonRT01_Kelompok2.setEnabled(true);
                    ButtonRT02_Kelompok2.setEnabled(false);
                    ButtonRT03_Kelompok2.setEnabled(false);
                    ButtonRT04_Kelompok2.setEnabled(false);
                    ButtonKKRT01_Kelompok2.setEnabled(true);
                    ButtonKKRT02_Kelompok2.setEnabled(false);
                    ButtonKKRT03_Kelompok2.setEnabled(false);
                    ButtonKKRT04_Kelompok2.setEnabled(false);
                    ButtonBRT01_Kelompok2.setEnabled(true);
                    ButtonBRT02_Kelompok2.setEnabled(false);
                    ButtonBRT03_Kelompok2.setEnabled(false);
                    ButtonBRT04_Kelompok2.setEnabled(false);
                    ButtonLRT01_Kelompok2.setEnabled(true);
                    ButtonLRT02_Kelompok2.setEnabled(false);
                    ButtonLRT03_Kelompok2.setEnabled(false);
                    ButtonLRT04_Kelompok2.setEnabled(false);
                    DialogLogin_Kelompok2.setVisible(false);
                    TextFieldNama_Kelompok2.setText("");
                    PasswordFieldPIN_Kelompok2.setText("");
                    ComboBoxRT_Kelompok2.setSelectedItem("RT 01");
                }else if(ComboBoxRT_Kelompok2.getSelectedItem().equals("RT 02")){
                    ButtonRT01_Kelompok2.setEnabled(false);
                    ButtonRT02_Kelompok2.setEnabled(true);
                    ButtonRT03_Kelompok2.setEnabled(false);
                    ButtonRT04_Kelompok2.setEnabled(false);
                    ButtonKKRT01_Kelompok2.setEnabled(true);
                    ButtonKKRT02_Kelompok2.setEnabled(true);
                    ButtonKKRT03_Kelompok2.setEnabled(false);
                    ButtonKKRT04_Kelompok2.setEnabled(false);
                    ButtonBRT01_Kelompok2.setEnabled(false);
                    ButtonBRT02_Kelompok2.setEnabled(true);
                    ButtonBRT03_Kelompok2.setEnabled(false);
                    ButtonBRT04_Kelompok2.setEnabled(false);
                    ButtonLRT01_Kelompok2.setEnabled(false);
                    ButtonLRT02_Kelompok2.setEnabled(true);
                    ButtonLRT03_Kelompok2.setEnabled(false);
                    ButtonLRT04_Kelompok2.setEnabled(false);
                    DialogLogin_Kelompok2.setVisible(false);
                    TextFieldNama_Kelompok2.setText("");
                    PasswordFieldPIN_Kelompok2.setText("");
                    ComboBoxRT_Kelompok2.setSelectedItem("RT 01");
                }else if(ComboBoxRT_Kelompok2.getSelectedItem().equals("RT 03")){
                   ButtonRT01_Kelompok2.setEnabled(false);
                    ButtonRT02_Kelompok2.setEnabled(false);
                    ButtonRT03_Kelompok2.setEnabled(true);
                    ButtonRT04_Kelompok2.setEnabled(false);
                    ButtonKKRT01_Kelompok2.setEnabled(false);
                    ButtonKKRT02_Kelompok2.setEnabled(false);
                    ButtonKKRT03_Kelompok2.setEnabled(true);
                    ButtonKKRT04_Kelompok2.setEnabled(false);
                    ButtonBRT01_Kelompok2.setEnabled(false);
                    ButtonBRT02_Kelompok2.setEnabled(false);
                    ButtonBRT03_Kelompok2.setEnabled(true);
                    ButtonBRT04_Kelompok2.setEnabled(false);
                    ButtonLRT01_Kelompok2.setEnabled(false);
                    ButtonLRT02_Kelompok2.setEnabled(false);
                    ButtonLRT03_Kelompok2.setEnabled(true);
                    ButtonLRT04_Kelompok2.setEnabled(false);
                    DialogLogin_Kelompok2.setVisible(false);
                    TextFieldNama_Kelompok2.setText("");
                    PasswordFieldPIN_Kelompok2.setText("");
                    ComboBoxRT_Kelompok2.setSelectedItem("RT 01");
                }else if(ComboBoxRT_Kelompok2.getSelectedItem().equals("RT 04")){
                    ButtonRT01_Kelompok2.setEnabled(false);
                    ButtonRT02_Kelompok2.setEnabled(false);
                    ButtonRT03_Kelompok2.setEnabled(false);
                    ButtonRT04_Kelompok2.setEnabled(true);
                    ButtonKKRT01_Kelompok2.setEnabled(false);
                    ButtonKKRT02_Kelompok2.setEnabled(false);
                    ButtonKKRT03_Kelompok2.setEnabled(false);
                    ButtonKKRT04_Kelompok2.setEnabled(true);
                    ButtonBRT01_Kelompok2.setEnabled(false);
                    ButtonBRT02_Kelompok2.setEnabled(false);
                    ButtonBRT03_Kelompok2.setEnabled(false);
                    ButtonBRT04_Kelompok2.setEnabled(true);
                    ButtonLRT01_Kelompok2.setEnabled(false);
                    ButtonLRT02_Kelompok2.setEnabled(false);
                    ButtonLRT03_Kelompok2.setEnabled(false);
                    ButtonLRT04_Kelompok2.setEnabled(true);
                    DialogLogin_Kelompok2.setVisible(false);
                    TextFieldNama_Kelompok2.setText("");
                    PasswordFieldPIN_Kelompok2.setText("");
                    ComboBoxRT_Kelompok2.setSelectedItem("RT 01");
                }
            }else if((rs.getRow()==0)){
                JOptionPane.showMessageDialog(null,"Maaf, "
                    + "Gagal masuk Nama atau PIN "
                    + "atau RT Pengguna tidak sesuai ...!");
                    ButtonRT01_Kelompok2.setEnabled(false);
                    ButtonRT02_Kelompok2.setEnabled(false);
                    ButtonRT03_Kelompok2.setEnabled(false);
                    ButtonRT04_Kelompok2.setEnabled(false);
                    ButtonKKRT01_Kelompok2.setEnabled(false);
                    ButtonKKRT02_Kelompok2.setEnabled(false);
                    ButtonKKRT03_Kelompok2.setEnabled(false);
                    ButtonKKRT04_Kelompok2.setEnabled(false);
                    ButtonBRT01_Kelompok2.setEnabled(false);
                    ButtonBRT02_Kelompok2.setEnabled(false);
                    ButtonBRT03_Kelompok2.setEnabled(false);
                    ButtonBRT04_Kelompok2.setEnabled(false);
                    ButtonLRT01_Kelompok2.setEnabled(false);
                    ButtonLRT02_Kelompok2.setEnabled(false);
                    ButtonLRT03_Kelompok2.setEnabled(false);
                    ButtonLRT04_Kelompok2.setEnabled(false);
            }
        } catch (SQLException e) {
            System.out.println("Error" +e);
        }
    }//GEN-LAST:event_ButtonLogin_Kelompok3ActionPerformed

    private void ButtonRT01_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRT01_Kelompok2ActionPerformed
    Menu_RT01 MRT01 = new Menu_RT01();
    DesktopPane_Kelompok2.add(MRT01);
    MRT01.setVisible(true);
    }//GEN-LAST:event_ButtonRT01_Kelompok2ActionPerformed

    private void ButtonBRT01_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBRT01_Kelompok2ActionPerformed
    Bantuan_RT01 BRT01 = new Bantuan_RT01();
    DesktopPane_Kelompok2.add(BRT01);
    BRT01.setVisible(true);
    }//GEN-LAST:event_ButtonBRT01_Kelompok2ActionPerformed

    private void ButtonLRT01_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLRT01_Kelompok2ActionPerformed
    Laporan_RT01 LRT01 = new Laporan_RT01();
    DesktopPane_Kelompok2.add(LRT01);
    LRT01.setVisible(true);
    
    }//GEN-LAST:event_ButtonLRT01_Kelompok2ActionPerformed

    private void ButtonLogin_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogin_Kelompok2ActionPerformed
    DialogLogin_Kelompok2.setVisible(true);
    }//GEN-LAST:event_ButtonLogin_Kelompok2ActionPerformed

    private void ButtonKeluar_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKeluar_Kelompok2ActionPerformed
    this.dispose(); 
    MenuUtama MU = new MenuUtama(); 
    MU.setVisible(true);
    }//GEN-LAST:event_ButtonKeluar_Kelompok2ActionPerformed

    private void ButtonSO_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSO_Kelompok2ActionPerformed
    Struktur_Organisasi SO = new Struktur_Organisasi();
    DesktopPane_Kelompok2.add(SO);
    SO.setVisible(true);
    }//GEN-LAST:event_ButtonSO_Kelompok2ActionPerformed

    private void ButtonRT02_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRT02_Kelompok2ActionPerformed
    Menu_RT02 MRT02 = new Menu_RT02();
    DesktopPane_Kelompok2.add(MRT02);
    MRT02.setVisible(true);
    }//GEN-LAST:event_ButtonRT02_Kelompok2ActionPerformed

    private void ButtonRT03_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRT03_Kelompok2ActionPerformed
    Menu_RT03 MRT03 = new Menu_RT03();
    DesktopPane_Kelompok2.add(MRT03);
    MRT03.setVisible(true);
    }//GEN-LAST:event_ButtonRT03_Kelompok2ActionPerformed

    private void ButtonRT04_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRT04_Kelompok2ActionPerformed
    Menu_RT04 MRT04 = new Menu_RT04();
    DesktopPane_Kelompok2.add(MRT04);
    MRT04.setVisible(true);
    }//GEN-LAST:event_ButtonRT04_Kelompok2ActionPerformed

    private void ButtonKKRT02_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKKRT02_Kelompok2ActionPerformed
    Keluarga_RT02 KKRT02 = new Keluarga_RT02();
    DesktopPane_Kelompok2.add(KKRT02);
    KKRT02.setVisible(true);
    }//GEN-LAST:event_ButtonKKRT02_Kelompok2ActionPerformed

    private void ButtonKKRT03_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKKRT03_Kelompok2ActionPerformed
    Keluarga_RT03 KKRT03 = new Keluarga_RT03();
    DesktopPane_Kelompok2.add(KKRT03);
    KKRT03.setVisible(true);
    }//GEN-LAST:event_ButtonKKRT03_Kelompok2ActionPerformed

    private void ButtonKKRT04_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKKRT04_Kelompok2ActionPerformed
    Keluarga_RT04 KKRT04 = new Keluarga_RT04();
    DesktopPane_Kelompok2.add(KKRT04);
    KKRT04.setVisible(true);
    }//GEN-LAST:event_ButtonKKRT04_Kelompok2ActionPerformed

    private void ButtonBRT02_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBRT02_Kelompok2ActionPerformed
    Bantuan_RT02 BRT02 = new Bantuan_RT02();
    DesktopPane_Kelompok2.add(BRT02);
    BRT02.setVisible(true);
    }//GEN-LAST:event_ButtonBRT02_Kelompok2ActionPerformed

    private void ButtonBRT03_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBRT03_Kelompok2ActionPerformed
    Bantuan_RT03 BRT03 = new Bantuan_RT03();
    DesktopPane_Kelompok2.add(BRT03);
    BRT03.setVisible(true);
    }//GEN-LAST:event_ButtonBRT03_Kelompok2ActionPerformed

    private void ButtonBRT04_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBRT04_Kelompok2ActionPerformed
    Bantuan_RT04 BRT04 = new Bantuan_RT04();
    DesktopPane_Kelompok2.add(BRT04);
    BRT04.setVisible(true);
    }//GEN-LAST:event_ButtonBRT04_Kelompok2ActionPerformed

    private void ButtonLRT02_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLRT02_Kelompok2ActionPerformed
    Laporan_RT02 LRT02 = new Laporan_RT02();
    DesktopPane_Kelompok2.add(LRT02);
    LRT02.setVisible(true);
    }//GEN-LAST:event_ButtonLRT02_Kelompok2ActionPerformed

    private void ButtonLRT03_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLRT03_Kelompok2ActionPerformed
    Laporan_RT03 LRT03 = new Laporan_RT03();
    DesktopPane_Kelompok2.add(LRT03);
    LRT03.setVisible(true);
    }//GEN-LAST:event_ButtonLRT03_Kelompok2ActionPerformed

    private void ButtonLRT04_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLRT04_Kelompok2ActionPerformed
    Laporan_RT04 LRT04 = new Laporan_RT04();
    DesktopPane_Kelompok2.add(LRT04);
    LRT04.setVisible(true);
    }//GEN-LAST:event_ButtonLRT04_Kelompok2ActionPerformed

    private void ButtonBatal_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBatal_Kelompok2ActionPerformed
    DialogLogin_Kelompok2.dispose();
    }//GEN-LAST:event_ButtonBatal_Kelompok2ActionPerformed

    private void ButtonDev_Kelompok3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDev_Kelompok3ActionPerformed
    Developer dev = new Developer();
    DesktopPane_Kelompok2.add(dev);
    dev.setVisible(true);
    }//GEN-LAST:event_ButtonDev_Kelompok3ActionPerformed

    private void ButtonBantuan_Kelompok3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBantuan_Kelompok3ActionPerformed
    Bantuan ban = new Bantuan();
    DesktopPane_Kelompok2.add(ban);
    ban.setVisible(true);
    }//GEN-LAST:event_ButtonBantuan_Kelompok3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ButtonBRT01_Kelompok2;
    private javax.swing.JButton ButtonBRT02_Kelompok2;
    private javax.swing.JButton ButtonBRT03_Kelompok2;
    private javax.swing.JButton ButtonBRT04_Kelompok2;
    private javax.swing.JButton ButtonBantuan_Kelompok3;
    private javax.swing.JButton ButtonBatal_Kelompok2;
    private javax.swing.JButton ButtonDev_Kelompok3;
    public javax.swing.JButton ButtonKKRT01_Kelompok2;
    private javax.swing.JButton ButtonKKRT02_Kelompok2;
    private javax.swing.JButton ButtonKKRT03_Kelompok2;
    private javax.swing.JButton ButtonKKRT04_Kelompok2;
    private javax.swing.JButton ButtonKeluar_Kelompok2;
    public javax.swing.JButton ButtonLRT01_Kelompok2;
    private javax.swing.JButton ButtonLRT02_Kelompok2;
    private javax.swing.JButton ButtonLRT03_Kelompok2;
    private javax.swing.JButton ButtonLRT04_Kelompok2;
    private javax.swing.JButton ButtonLogin_Kelompok2;
    private javax.swing.JButton ButtonLogin_Kelompok3;
    public javax.swing.JButton ButtonRT01_Kelompok2;
    private javax.swing.JButton ButtonRT02_Kelompok2;
    private javax.swing.JButton ButtonRT03_Kelompok2;
    private javax.swing.JButton ButtonRT04_Kelompok2;
    private javax.swing.JButton ButtonSO_Kelompok2;
    private javax.swing.JComboBox<String> ComboBoxRT_Kelompok2;
    private javax.swing.JDesktopPane DesktopPane_Kelompok2;
    private javax.swing.JDialog DialogLogin_Kelompok2;
    private javax.swing.JLabel LabelJudul1;
    private javax.swing.JLabel LabelJudul1_Kelompok3;
    private javax.swing.JLabel LabelJudul2_Kelompok2;
    private javax.swing.JLabel LabelJudul3_Kelompok2;
    private javax.swing.JLabel LabelJudul4_Kelompok2;
    private javax.swing.JLabel LabelLogo1_Kelompok2;
    private javax.swing.JLabel LabelLogo2_Kelompok2;
    private javax.swing.JLabel LabelNama_Kelompok2;
    private javax.swing.JLabel LabelPIN_Kelompok2;
    private javax.swing.JLabel LabelRT_Kelompok2;
    private javax.swing.JPanel PanelGaris1_Kelompok2;
    private javax.swing.JPanel PanelGaris2_Kelompok2;
    private javax.swing.JPanel PanelGaris3_Kelompok2;
    private javax.swing.JPanel PanelHeader2_Kelompok2;
    private javax.swing.JPanel PanelHeader_Kelompok2;
    private javax.swing.JPanel PanelMenu_Kelompok2;
    private javax.swing.JPanel PanelMenu_Kelompok3;
    private javax.swing.JPanel PanelUtama_Kelompok2;
    private javax.swing.JPasswordField PasswordFieldPIN_Kelompok2;
    private javax.swing.JTextField TextFieldNama_Kelompok2;
    // End of variables declaration//GEN-END:variables
}
