/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Index;

/**
 *
 * @author MD
 */
public class Struktur_Organisasi extends javax.swing.JInternalFrame {

    /**
     * Creates new form Struktur_Organisasi
     */
    public Struktur_Organisasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ButtonTutup_Kelompok2 = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MD\\Pictures\\Untitled.png")); // NOI18N

        ButtonTutup_Kelompok2.setText("TUTUP");
        ButtonTutup_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTutup_Kelompok2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonTutup_Kelompok2)
                .addGap(212, 212, 212))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonTutup_Kelompok2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonTutup_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTutup_Kelompok2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_ButtonTutup_Kelompok2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonTutup_Kelompok2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
