/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Keluarga;

import Database.Koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MD
 */
public class Keluarga_RT02 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Keluarga_RT02
     */
    public Keluarga_RT02() {
        initComponents();
        LoadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogInputData_Kelompok2 = new javax.swing.JDialog();
        PanelInputData_Kelompok2 = new javax.swing.JPanel();
        LabelNoKK_Kelompok2 = new javax.swing.JLabel();
        LabelKepalaKeluarga_Kelompok2 = new javax.swing.JLabel();
        ButtonSimpan_Kelompok2 = new javax.swing.JButton();
        TextFieldNoKK_Kelompok2 = new javax.swing.JTextField();
        TextFieldKepalaKeluarga_Kelompok2 = new javax.swing.JTextField();
        ButtonBatal_Kelompok2 = new javax.swing.JButton();
        ButtonEdit_Kelompok2 = new javax.swing.JButton();
        PanelKeluargaRT02_Kelompok2 = new javax.swing.JPanel();
        PanelHeader_Kelompok2 = new javax.swing.JPanel();
        LabelLogo1_Kelompok2 = new javax.swing.JLabel();
        LabelLogo2_Kelompok2 = new javax.swing.JLabel();
        LabelJudul1_Kelompok2 = new javax.swing.JLabel();
        LabelJudul_Kelompok2 = new javax.swing.JLabel();
        ScrollPane_Kelompok2 = new javax.swing.JScrollPane();
        TabelKeluargaRT02_Kelompok2 = new javax.swing.JTable();
        TextFieldCari_Kelompok2 = new javax.swing.JTextField();
        ButtonCari_Kelompok2 = new javax.swing.JButton();
        ButtonInput_Kelompok2 = new javax.swing.JButton();
        ButtonTutup_Kelompok2 = new javax.swing.JButton();
        ButtonHapus_Kelompok2 = new javax.swing.JButton();

        DialogInputData_Kelompok2.setMinimumSize(new java.awt.Dimension(350, 200));

        LabelNoKK_Kelompok2.setText("No KK");

        LabelKepalaKeluarga_Kelompok2.setText("Kepala Keluarga");

        ButtonSimpan_Kelompok2.setText("Simpan");
        ButtonSimpan_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSimpan_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonBatal_Kelompok2.setText("Batal");
        ButtonBatal_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBatal_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonEdit_Kelompok2.setText("Edit");
        ButtonEdit_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEdit_Kelompok2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelInputData_Kelompok2Layout = new javax.swing.GroupLayout(PanelInputData_Kelompok2);
        PanelInputData_Kelompok2.setLayout(PanelInputData_Kelompok2Layout);
        PanelInputData_Kelompok2Layout.setHorizontalGroup(
            PanelInputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInputData_Kelompok2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelKepalaKeluarga_Kelompok2)
                    .addComponent(LabelNoKK_Kelompok2))
                .addGap(18, 18, 18)
                .addGroup(PanelInputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextFieldNoKK_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(TextFieldKepalaKeluarga_Kelompok2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelInputData_Kelompok2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(ButtonSimpan_Kelompok2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonEdit_Kelompok2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(ButtonBatal_Kelompok2)
                .addContainerGap())
        );
        PanelInputData_Kelompok2Layout.setVerticalGroup(
            PanelInputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInputData_Kelompok2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNoKK_Kelompok2)
                    .addComponent(TextFieldNoKK_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelInputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelKepalaKeluarga_Kelompok2)
                    .addComponent(TextFieldKepalaKeluarga_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelInputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSimpan_Kelompok2)
                    .addComponent(ButtonBatal_Kelompok2)
                    .addComponent(ButtonEdit_Kelompok2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DialogInputData_Kelompok2Layout = new javax.swing.GroupLayout(DialogInputData_Kelompok2.getContentPane());
        DialogInputData_Kelompok2.getContentPane().setLayout(DialogInputData_Kelompok2Layout);
        DialogInputData_Kelompok2Layout.setHorizontalGroup(
            DialogInputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelInputData_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogInputData_Kelompok2Layout.setVerticalGroup(
            DialogInputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelInputData_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(919, 631));

        PanelKeluargaRT02_Kelompok2.setBackground(new java.awt.Color(0, 102, 102));

        PanelHeader_Kelompok2.setBackground(new java.awt.Color(0, 204, 204));

        LabelLogo1_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Screenshot_20220716-102029_1 - Copy.jpg"))); // NOI18N

        LabelLogo2_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Screenshot_20220716-102029_1 - Copy.jpg"))); // NOI18N

        LabelJudul1_Kelompok2.setBackground(new java.awt.Color(0, 102, 102));
        LabelJudul1_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelJudul1_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        LabelJudul1_Kelompok2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelJudul1_Kelompok2.setText("<html> <center>KK - RT 02</center> </html> ");

        javax.swing.GroupLayout PanelHeader_Kelompok2Layout = new javax.swing.GroupLayout(PanelHeader_Kelompok2);
        PanelHeader_Kelompok2.setLayout(PanelHeader_Kelompok2Layout);
        PanelHeader_Kelompok2Layout.setHorizontalGroup(
            PanelHeader_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelJudul1_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
            .addGroup(PanelHeader_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelHeader_Kelompok2Layout.createSequentialGroup()
                    .addComponent(LabelLogo1_Kelompok2)
                    .addGap(0, 372, Short.MAX_VALUE)))
            .addGroup(PanelHeader_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHeader_Kelompok2Layout.createSequentialGroup()
                    .addGap(0, 372, Short.MAX_VALUE)
                    .addComponent(LabelLogo2_Kelompok2)))
        );
        PanelHeader_Kelompok2Layout.setVerticalGroup(
            PanelHeader_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelJudul1_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(PanelHeader_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelHeader_Kelompok2Layout.createSequentialGroup()
                    .addComponent(LabelLogo1_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(PanelHeader_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelHeader_Kelompok2Layout.createSequentialGroup()
                    .addComponent(LabelLogo2_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        LabelJudul_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelJudul_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        LabelJudul_Kelompok2.setText("DATA KELUWARGA RT 02");

        TabelKeluargaRT02_Kelompok2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No KK", "Kepala Keluarga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelKeluargaRT02_Kelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelKeluargaRT02_Kelompok2MouseClicked(evt);
            }
        });
        ScrollPane_Kelompok2.setViewportView(TabelKeluargaRT02_Kelompok2);

        ButtonCari_Kelompok2.setBackground(new java.awt.Color(0, 102, 102));
        ButtonCari_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonCari_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCari_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/find-my-friend.png"))); // NOI18N
        ButtonCari_Kelompok2.setText("Cari");
        ButtonCari_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCari_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonInput_Kelompok2.setBackground(new java.awt.Color(0, 102, 102));
        ButtonInput_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonInput_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonInput_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/input.png"))); // NOI18N
        ButtonInput_Kelompok2.setText("Input Data ");
        ButtonInput_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInput_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonTutup_Kelompok2.setBackground(new java.awt.Color(0, 102, 102));
        ButtonTutup_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonTutup_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonTutup_Kelompok2.setText("TUTUP");
        ButtonTutup_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTutup_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonHapus_Kelompok2.setBackground(new java.awt.Color(0, 102, 102));
        ButtonHapus_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonHapus_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonHapus_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/delete.png"))); // NOI18N
        ButtonHapus_Kelompok2.setText("Hapus Data");
        ButtonHapus_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHapus_Kelompok2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelKeluargaRT02_Kelompok2Layout = new javax.swing.GroupLayout(PanelKeluargaRT02_Kelompok2);
        PanelKeluargaRT02_Kelompok2.setLayout(PanelKeluargaRT02_Kelompok2Layout);
        PanelKeluargaRT02_Kelompok2Layout.setHorizontalGroup(
            PanelKeluargaRT02_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKeluargaRT02_Kelompok2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelKeluargaRT02_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPane_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, 883, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKeluargaRT02_Kelompok2Layout.createSequentialGroup()
                        .addComponent(LabelJudul_Kelompok2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonCari_Kelompok2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldCari_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelKeluargaRT02_Kelompok2Layout.createSequentialGroup()
                        .addComponent(ButtonInput_Kelompok2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonTutup_Kelompok2)
                        .addGap(261, 261, 261)
                        .addComponent(ButtonHapus_Kelompok2)))
                .addContainerGap())
            .addGroup(PanelKeluargaRT02_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelHeader_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelKeluargaRT02_Kelompok2Layout.setVerticalGroup(
            PanelKeluargaRT02_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKeluargaRT02_Kelompok2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(PanelKeluargaRT02_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCari_Kelompok2)
                    .addComponent(TextFieldCari_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelJudul_Kelompok2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPane_Kelompok2)
                .addGap(18, 18, 18)
                .addGroup(PanelKeluargaRT02_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonTutup_Kelompok2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelKeluargaRT02_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonInput_Kelompok2)
                        .addComponent(ButtonHapus_Kelompok2)))
                .addContainerGap())
            .addGroup(PanelKeluargaRT02_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelKeluargaRT02_Kelompok2Layout.createSequentialGroup()
                    .addComponent(PanelHeader_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 369, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelKeluargaRT02_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelKeluargaRT02_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSimpan_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSimpan_Kelompok2ActionPerformed
        try {
            String sql = "INSERT INTO keluarga_rt02 VALUES ('"+TextFieldNoKK_Kelompok2.getText()+"','"
            +TextFieldKepalaKeluarga_Kelompok2.getText()+"')";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Masukan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        LoadTable();
    }//GEN-LAST:event_ButtonSimpan_Kelompok2ActionPerformed

    private void ButtonBatal_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBatal_Kelompok2ActionPerformed
        DialogInputData_Kelompok2.dispose();
    }//GEN-LAST:event_ButtonBatal_Kelompok2ActionPerformed

    private void ButtonEdit_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEdit_Kelompok2ActionPerformed
        try {
            String sql ="UPDATE keluarga_rt02 SET NoKK = '"+TextFieldNoKK_Kelompok2.getText()+
            "',Kepala_Keluarga = '"+TextFieldKepalaKeluarga_Kelompok2.getText()+
            "' WHERE NoKK = '"+TextFieldNoKK_Kelompok2.getText()+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Diedit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Edit Data Gagal!!!"+e.getMessage());
        }
        LoadTable();
    }//GEN-LAST:event_ButtonEdit_Kelompok2ActionPerformed

    private void TabelKeluargaRT02_Kelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelKeluargaRT02_Kelompok2MouseClicked
        int baris = TabelKeluargaRT02_Kelompok2.rowAtPoint(evt.getPoint());
        String NoKK =TabelKeluargaRT02_Kelompok2.getValueAt(baris, 0).toString();
        TextFieldNoKK_Kelompok2.setText(NoKK);
        String Kepala_Keluarga = TabelKeluargaRT02_Kelompok2.getValueAt(baris,1).toString();
        TextFieldKepalaKeluarga_Kelompok2.setText(Kepala_Keluarga);
    }//GEN-LAST:event_TabelKeluargaRT02_Kelompok2MouseClicked

    private void ButtonCari_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCari_Kelompok2ActionPerformed
        String key=TextFieldCari_Kelompok2.getText();
        System.out.println(key);

        if(key!=""){
            FindData(key);
        }else{
            LoadTable();
        }
    }//GEN-LAST:event_ButtonCari_Kelompok2ActionPerformed

    private void ButtonInput_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInput_Kelompok2ActionPerformed
        DialogInputData_Kelompok2.setVisible(true);
    }//GEN-LAST:event_ButtonInput_Kelompok2ActionPerformed

    private void ButtonTutup_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTutup_Kelompok2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_ButtonTutup_Kelompok2ActionPerformed

    private void ButtonHapus_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapus_Kelompok2ActionPerformed
        try {
            String sql ="delete from keluarga_rt02 where NoKK='"+TextFieldNoKK_Kelompok2.getText()+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Data Dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        LoadTable();
    }//GEN-LAST:event_ButtonHapus_Kelompok2ActionPerformed

     public final void LoadTable() {
        DefaultTableModel model = new DefaultTableModel();
        TabelKeluargaRT02_Kelompok2.setModel(model);
        model.addColumn("No KK");
        model.addColumn("Kepala Keluarga");
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection c = Koneksi.configDB();
            Statement s = c.createStatement();

            String sql = "SELECT * FROM keluarga_rt02";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                Object[] o = new Object[2];
                o[0] = r.getString("NoKK");
                o[1] = r.getString("Kepala_Keluarga");
               
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terdapat Kesalahan, Harap Periksa Lagi Program/Kodingannya");
        }
    }
    
    private void FindData(String key){
        try{
            DefaultTableModel model = new DefaultTableModel();
            Object[] judul_kolom = {"NoKK", "Kepala Keluarga"};
            model=new DefaultTableModel(null,judul_kolom);
            TabelKeluargaRT02_Kelompok2.setModel(model);
            
            Connection conn=(Connection)Koneksi.configDB();
            Statement stt=conn.createStatement();
            model.getDataVector().removeAllElements();
            
            String sql = ("SELECT * from keluarga_rt02 WHERE NoKK LIKE '%"+key+"%' OR Kepala_Keluarga LIKE '%"+key+"%'");  
            ResultSet rs = stt.executeQuery(sql);
            while(rs.next()){
                Object[] data={
                    rs.getString("NoKK"),
                    rs.getString("Kepala_Keluarga"),
                };
               model.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBatal_Kelompok2;
    private javax.swing.JButton ButtonCari_Kelompok2;
    private javax.swing.JButton ButtonEdit_Kelompok2;
    private javax.swing.JButton ButtonHapus_Kelompok2;
    private javax.swing.JButton ButtonInput_Kelompok2;
    private javax.swing.JButton ButtonSimpan_Kelompok2;
    private javax.swing.JButton ButtonTutup_Kelompok2;
    private javax.swing.JDialog DialogInputData_Kelompok2;
    private javax.swing.JLabel LabelJudul1_Kelompok2;
    private javax.swing.JLabel LabelJudul_Kelompok2;
    private javax.swing.JLabel LabelKepalaKeluarga_Kelompok2;
    private javax.swing.JLabel LabelLogo1_Kelompok2;
    private javax.swing.JLabel LabelLogo2_Kelompok2;
    private javax.swing.JLabel LabelNoKK_Kelompok2;
    private javax.swing.JPanel PanelHeader_Kelompok2;
    private javax.swing.JPanel PanelInputData_Kelompok2;
    private javax.swing.JPanel PanelKeluargaRT02_Kelompok2;
    private javax.swing.JScrollPane ScrollPane_Kelompok2;
    private javax.swing.JTable TabelKeluargaRT02_Kelompok2;
    private javax.swing.JTextField TextFieldCari_Kelompok2;
    private javax.swing.JTextField TextFieldKepalaKeluarga_Kelompok2;
    private javax.swing.JTextField TextFieldNoKK_Kelompok2;
    // End of variables declaration//GEN-END:variables
}
