/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Warga;

import Database.Koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MD
 */
public class Menu_RT04 extends javax.swing.JInternalFrame {

    
    String JK;
    public Menu_RT04() {
        initComponents();
        LoadTable();
        LoadTableKK();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGroup_Kelompok2 = new javax.swing.ButtonGroup();
        InputData_Kelompok2 = new javax.swing.JFrame();
        LabelNoKK_Kelompok2 = new javax.swing.JLabel();
        Kelompok2_LabelJudulInput1 = new javax.swing.JLabel();
        LabelNIK_Kelompok2 = new javax.swing.JLabel();
        LabelNama_Kelompok2 = new javax.swing.JLabel();
        LabelJK_Kelompok2 = new javax.swing.JLabel();
        LabelUmur_Kelompok2 = new javax.swing.JLabel();
        LabelStatus_Kelompok2 = new javax.swing.JLabel();
        TextFieldUmur_Kelompok2 = new javax.swing.JTextField();
        TextFieldNama_Kelompok2 = new javax.swing.JTextField();
        TextFieldNIK_Kelompok2 = new javax.swing.JTextField();
        RadioLaki_Kelompok2 = new javax.swing.JRadioButton();
        RadioPerempuan_Kelompok2 = new javax.swing.JRadioButton();
        ComboBoxStatus_Kelompok2 = new javax.swing.JComboBox<>();
        ButtonSimpan_Kelompok2 = new javax.swing.JButton();
        ButtonBatal_Kelompok2 = new javax.swing.JButton();
        ButtonEdit_Kelompok2 = new javax.swing.JButton();
        TextFieldNoKK_Kelompok2 = new javax.swing.JTextField();
        ButtonCek_Kelompok2 = new javax.swing.JButton();
        ButtonBersih_Kelompok2 = new javax.swing.JButton();
        TabelKK_Kelompok2 = new javax.swing.JFrame();
        ScrollPane_Kelompok2 = new javax.swing.JScrollPane();
        TabelKeluargaRT04_Kelompok2 = new javax.swing.JTable();
        LabelJudul2_Kelompok2 = new javax.swing.JLabel();
        ButtonCari2_Kelompok2 = new javax.swing.JButton();
        TextFieldCari2_Kelompok2 = new javax.swing.JTextField();
        PanelRT04_Kelompok2 = new javax.swing.JPanel();
        LabelJudul_Kelompok2 = new javax.swing.JLabel();
        ScrollPaneTable_Kelompok2 = new javax.swing.JScrollPane();
        TabelWargaRT04_Kelompok2 = new javax.swing.JTable();
        TextFieldCari_Kelompok2 = new javax.swing.JTextField();
        ButtonCari_Kelompok2 = new javax.swing.JButton();
        ButtonInputNIK_Kelompok2 = new javax.swing.JButton();
        ButtonTutup_Kelompok2 = new javax.swing.JButton();
        ButtonNIK_Kelompok2 = new javax.swing.JButton();
        PanelHeader_Kelompok2 = new javax.swing.JPanel();
        LabelLogo1_Kelompok2 = new javax.swing.JLabel();
        LabelLogo2_Kelompok2 = new javax.swing.JLabel();
        LabelJudul1_Kelompok2 = new javax.swing.JLabel();

        InputData_Kelompok2.setMinimumSize(new java.awt.Dimension(365, 400));

        LabelNoKK_Kelompok2.setText("No KK");

        Kelompok2_LabelJudulInput1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Kelompok2_LabelJudulInput1.setText("Input Data Warga");

        LabelNIK_Kelompok2.setText("NIK");

        LabelNama_Kelompok2.setText("Nama");

        LabelJK_Kelompok2.setText("Jenis Kelamin");

        LabelUmur_Kelompok2.setText("Umur");

        LabelStatus_Kelompok2.setText("Status Hubungan");

        ButtonGroup_Kelompok2.add(RadioLaki_Kelompok2);
        RadioLaki_Kelompok2.setText("Laki-Laki");
        RadioLaki_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioLaki_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonGroup_Kelompok2.add(RadioPerempuan_Kelompok2);
        RadioPerempuan_Kelompok2.setText("Perempuan");
        RadioPerempuan_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioPerempuan_Kelompok2ActionPerformed(evt);
            }
        });

        ComboBoxStatus_Kelompok2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Kepala Keluarga", "Istri", "Anak" }));

        ButtonSimpan_Kelompok2.setText("Simpan");
        ButtonSimpan_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSimpan_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonBatal_Kelompok2.setText("Batal");
        ButtonBatal_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBatal_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonEdit_Kelompok2.setText("Edit");
        ButtonEdit_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEdit_Kelompok2ActionPerformed(evt);
            }
        });

        TextFieldNoKK_Kelompok2.setEditable(false);

        ButtonCek_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/find-my-friend.png"))); // NOI18N
        ButtonCek_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCek_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonBersih_Kelompok2.setText("Bersih");
        ButtonBersih_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBersih_Kelompok2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InputData_Kelompok2Layout = new javax.swing.GroupLayout(InputData_Kelompok2.getContentPane());
        InputData_Kelompok2.getContentPane().setLayout(InputData_Kelompok2Layout);
        InputData_Kelompok2Layout.setHorizontalGroup(
            InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputData_Kelompok2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Kelompok2_LabelJudulInput1)
                    .addGroup(InputData_Kelompok2Layout.createSequentialGroup()
                        .addGroup(InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelStatus_Kelompok2)
                            .addComponent(LabelUmur_Kelompok2)
                            .addComponent(LabelJK_Kelompok2)
                            .addComponent(LabelNama_Kelompok2)
                            .addComponent(LabelNIK_Kelompok2)
                            .addComponent(LabelNoKK_Kelompok2))
                        .addGap(18, 18, 18)
                        .addGroup(InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InputData_Kelompok2Layout.createSequentialGroup()
                                .addGroup(InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ButtonEdit_Kelompok2)
                                    .addComponent(TextFieldNIK_Kelompok2)
                                    .addComponent(TextFieldNama_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addGroup(InputData_Kelompok2Layout.createSequentialGroup()
                                        .addComponent(RadioLaki_Kelompok2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RadioPerempuan_Kelompok2))
                                    .addComponent(ComboBoxStatus_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextFieldUmur_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextFieldNoKK_Kelompok2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonCek_Kelompok2))
                            .addGroup(InputData_Kelompok2Layout.createSequentialGroup()
                                .addComponent(ButtonSimpan_Kelompok2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonBatal_Kelompok2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonBersih_Kelompok2)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        InputData_Kelompok2Layout.setVerticalGroup(
            InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputData_Kelompok2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Kelompok2_LabelJudulInput1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelNoKK_Kelompok2)
                        .addComponent(TextFieldNoKK_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ButtonCek_Kelompok2))
                .addGap(10, 10, 10)
                .addGroup(InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNIK_Kelompok2)
                    .addComponent(TextFieldNIK_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNama_Kelompok2)
                    .addComponent(TextFieldNama_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelJK_Kelompok2)
                    .addComponent(RadioLaki_Kelompok2)
                    .addComponent(RadioPerempuan_Kelompok2))
                .addGap(18, 18, 18)
                .addGroup(InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelUmur_Kelompok2)
                    .addComponent(TextFieldUmur_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelStatus_Kelompok2)
                    .addComponent(ComboBoxStatus_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSimpan_Kelompok2)
                    .addComponent(ButtonBatal_Kelompok2)
                    .addComponent(ButtonBersih_Kelompok2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonEdit_Kelompok2))
        );

        TabelKK_Kelompok2.setLocation(new java.awt.Point(361, 5));
        TabelKK_Kelompok2.setMinimumSize(new java.awt.Dimension(500, 340));

        TabelKeluargaRT04_Kelompok2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No KK", "Kepala Keluarga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelKeluargaRT04_Kelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelKeluargaRT04_Kelompok2MouseClicked(evt);
            }
        });
        ScrollPane_Kelompok2.setViewportView(TabelKeluargaRT04_Kelompok2);

        LabelJudul2_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelJudul2_Kelompok2.setText("Data Keluarga RT 04");

        ButtonCari2_Kelompok2.setBackground(new java.awt.Color(0, 102, 102));
        ButtonCari2_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonCari2_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCari2_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/find-my-friend.png"))); // NOI18N
        ButtonCari2_Kelompok2.setText("Cari");
        ButtonCari2_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCari2_Kelompok2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TabelKK_Kelompok2Layout = new javax.swing.GroupLayout(TabelKK_Kelompok2.getContentPane());
        TabelKK_Kelompok2.getContentPane().setLayout(TabelKK_Kelompok2Layout);
        TabelKK_Kelompok2Layout.setHorizontalGroup(
            TabelKK_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollPane_Kelompok2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabelKK_Kelompok2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelJudul2_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonCari2_Kelompok2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextFieldCari2_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TabelKK_Kelompok2Layout.setVerticalGroup(
            TabelKK_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabelKK_Kelompok2Layout.createSequentialGroup()
                .addGroup(TabelKK_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFieldCari2_Kelompok2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TabelKK_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonCari2_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelJudul2_Kelompok2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPane_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setMaximizable(true);

        PanelRT04_Kelompok2.setBackground(new java.awt.Color(0, 102, 102));

        LabelJudul_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelJudul_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        LabelJudul_Kelompok2.setText("DATA WARGA RT 04");

        TabelWargaRT04_Kelompok2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No KK", "NIK", "Nama", "Jenis Kelamin", "Umur", "Status Hubungan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelWargaRT04_Kelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelWargaRT04_Kelompok2MouseClicked(evt);
            }
        });
        ScrollPaneTable_Kelompok2.setViewportView(TabelWargaRT04_Kelompok2);

        ButtonCari_Kelompok2.setBackground(new java.awt.Color(0, 102, 102));
        ButtonCari_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonCari_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCari_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/find-my-friend.png"))); // NOI18N
        ButtonCari_Kelompok2.setText("Cari");
        ButtonCari_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCari_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonInputNIK_Kelompok2.setBackground(new java.awt.Color(0, 102, 102));
        ButtonInputNIK_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonInputNIK_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonInputNIK_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/input.png"))); // NOI18N
        ButtonInputNIK_Kelompok2.setText("Input Data NIK");
        ButtonInputNIK_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInputNIK_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonTutup_Kelompok2.setBackground(new java.awt.Color(0, 102, 102));
        ButtonTutup_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonTutup_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonTutup_Kelompok2.setText("TUTUP");
        ButtonTutup_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTutup_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonNIK_Kelompok2.setBackground(new java.awt.Color(0, 102, 102));
        ButtonNIK_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonNIK_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonNIK_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/delete.png"))); // NOI18N
        ButtonNIK_Kelompok2.setText("Hapus Data NIK");
        ButtonNIK_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNIK_Kelompok2ActionPerformed(evt);
            }
        });

        PanelHeader_Kelompok2.setBackground(new java.awt.Color(0, 204, 204));

        LabelLogo1_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Screenshot_20220716-102029_1 - Copy.jpg"))); // NOI18N

        LabelLogo2_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Screenshot_20220716-102029_1 - Copy.jpg"))); // NOI18N

        LabelJudul1_Kelompok2.setBackground(new java.awt.Color(0, 102, 102));
        LabelJudul1_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelJudul1_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        LabelJudul1_Kelompok2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelJudul1_Kelompok2.setText("<html> <center>RT-04</center> </html> ");

        javax.swing.GroupLayout PanelHeader_Kelompok2Layout = new javax.swing.GroupLayout(PanelHeader_Kelompok2);
        PanelHeader_Kelompok2.setLayout(PanelHeader_Kelompok2Layout);
        PanelHeader_Kelompok2Layout.setHorizontalGroup(
            PanelHeader_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelJudul1_Kelompok2)
            .addGroup(PanelHeader_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelHeader_Kelompok2Layout.createSequentialGroup()
                    .addComponent(LabelLogo1_Kelompok2)
                    .addGap(0, 351, Short.MAX_VALUE)))
            .addGroup(PanelHeader_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHeader_Kelompok2Layout.createSequentialGroup()
                    .addGap(0, 351, Short.MAX_VALUE)
                    .addComponent(LabelLogo2_Kelompok2)))
        );
        PanelHeader_Kelompok2Layout.setVerticalGroup(
            PanelHeader_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeader_Kelompok2Layout.createSequentialGroup()
                .addComponent(LabelJudul1_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelHeader_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelHeader_Kelompok2Layout.createSequentialGroup()
                    .addComponent(LabelLogo1_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(PanelHeader_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelHeader_Kelompok2Layout.createSequentialGroup()
                    .addComponent(LabelLogo2_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout PanelRT04_Kelompok2Layout = new javax.swing.GroupLayout(PanelRT04_Kelompok2);
        PanelRT04_Kelompok2.setLayout(PanelRT04_Kelompok2Layout);
        PanelRT04_Kelompok2Layout.setHorizontalGroup(
            PanelRT04_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelHeader_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelRT04_Kelompok2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRT04_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPaneTable_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
                    .addGroup(PanelRT04_Kelompok2Layout.createSequentialGroup()
                        .addGroup(PanelRT04_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelRT04_Kelompok2Layout.createSequentialGroup()
                                .addComponent(LabelJudul_Kelompok2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonCari_Kelompok2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextFieldCari_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelRT04_Kelompok2Layout.createSequentialGroup()
                                .addComponent(ButtonInputNIK_Kelompok2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonNIK_Kelompok2)))
                        .addContainerGap())))
            .addGroup(PanelRT04_Kelompok2Layout.createSequentialGroup()
                .addGap(411, 411, 411)
                .addComponent(ButtonTutup_Kelompok2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelRT04_Kelompok2Layout.setVerticalGroup(
            PanelRT04_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRT04_Kelompok2Layout.createSequentialGroup()
                .addComponent(PanelHeader_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelRT04_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFieldCari_Kelompok2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelJudul_Kelompok2)
                    .addComponent(ButtonCari_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPaneTable_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addGroup(PanelRT04_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonInputNIK_Kelompok2)
                    .addComponent(ButtonNIK_Kelompok2))
                .addGap(16, 16, 16)
                .addComponent(ButtonTutup_Kelompok2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRT04_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRT04_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabelWargaRT04_Kelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelWargaRT04_Kelompok2MouseClicked
        int baris = TabelWargaRT04_Kelompok2.rowAtPoint(evt.getPoint());
        String NoKK =TabelWargaRT04_Kelompok2.getValueAt(baris, 0).toString();
        TextFieldNoKK_Kelompok2.setText(NoKK);
        String NIK = TabelWargaRT04_Kelompok2.getValueAt(baris,1).toString();
        TextFieldNIK_Kelompok2.setText(NIK);
        String Nama=TabelWargaRT04_Kelompok2.getValueAt(baris, 2).toString();
        TextFieldNama_Kelompok2.setText(Nama);
        String Umur=TabelWargaRT04_Kelompok2.getValueAt(baris, 4).toString();
        TextFieldUmur_Kelompok2.setText(Umur);
        String Status_Hubungan=TabelWargaRT04_Kelompok2.getValueAt(baris, 5).toString();
        ComboBoxStatus_Kelompok2.setSelectedItem(Status_Hubungan);
    }//GEN-LAST:event_TabelWargaRT04_Kelompok2MouseClicked

    private void ButtonCari_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCari_Kelompok2ActionPerformed
        String key=TextFieldCari_Kelompok2.getText();
        System.out.println(key);

        if(key!=""){
            FindData(key);
        }else{
            LoadTable();
        }
    }//GEN-LAST:event_ButtonCari_Kelompok2ActionPerformed

    private void ButtonInputNIK_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInputNIK_Kelompok2ActionPerformed
        InputData_Kelompok2.setVisible(true);
    }//GEN-LAST:event_ButtonInputNIK_Kelompok2ActionPerformed

    private void ButtonTutup_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTutup_Kelompok2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_ButtonTutup_Kelompok2ActionPerformed

    private void ButtonNIK_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNIK_Kelompok2ActionPerformed
        try {
            String sql ="delete from warga_rt04 where NIK='"+TextFieldNIK_Kelompok2.getText()+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Data Dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        LoadTable();
        bersih();
    }//GEN-LAST:event_ButtonNIK_Kelompok2ActionPerformed

    private void RadioLaki_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioLaki_Kelompok2ActionPerformed
    JK="Laki-Laki";
    }//GEN-LAST:event_RadioLaki_Kelompok2ActionPerformed

    private void RadioPerempuan_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioPerempuan_Kelompok2ActionPerformed
    JK="Perempuan";
    }//GEN-LAST:event_RadioPerempuan_Kelompok2ActionPerformed

    private void ButtonSimpan_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSimpan_Kelompok2ActionPerformed
    try {
            String sql = "INSERT INTO warga_rt04 VALUES ('"+TextFieldNoKK_Kelompok2.getText()+"','"
                    +TextFieldNIK_Kelompok2.getText()+"','"
                    +TextFieldNama_Kelompok2.getText()+"','"
                    +JK+"','"
                    +TextFieldUmur_Kelompok2.getText()+"','"
                    +ComboBoxStatus_Kelompok2.getSelectedItem()+"')";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil DiSimpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    LoadTable();
    bersih();
    }//GEN-LAST:event_ButtonSimpan_Kelompok2ActionPerformed

    private void ButtonBatal_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBatal_Kelompok2ActionPerformed
    InputData_Kelompok2.dispose();
    }//GEN-LAST:event_ButtonBatal_Kelompok2ActionPerformed

    private void ButtonEdit_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEdit_Kelompok2ActionPerformed
    try {
            String sql ="UPDATE warga_rt04 SET NoKK = '"+TextFieldNoKK_Kelompok2.getText()+
                    "',NIK = '"+TextFieldNIK_Kelompok2.getText()+
                    "',Nama= '"+TextFieldNama_Kelompok2.getText()+
                    "',Jenis_Kelamin= '"+JK+
                    "',Umur= '"+TextFieldUmur_Kelompok2.getText()+
                    "',Status_Hubungan= '"+ComboBoxStatus_Kelompok2.getSelectedItem()+
                    "' WHERE NIK = '"+TextFieldNIK_Kelompok2.getText()+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Diedit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Edit Data Gagal!!!"+e.getMessage());
        }
    LoadTable();
    bersih();
    }//GEN-LAST:event_ButtonEdit_Kelompok2ActionPerformed

    private void ButtonCek_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCek_Kelompok2ActionPerformed
    TabelKK_Kelompok2.setVisible(true);
    }//GEN-LAST:event_ButtonCek_Kelompok2ActionPerformed

    private void TabelKeluargaRT04_Kelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelKeluargaRT04_Kelompok2MouseClicked
     int baris = TabelKeluargaRT04_Kelompok2.rowAtPoint(evt.getPoint());
        String NoKK =TabelKeluargaRT04_Kelompok2.getValueAt(baris, 0).toString();
        TextFieldNoKK_Kelompok2.setText(NoKK);
    }//GEN-LAST:event_TabelKeluargaRT04_Kelompok2MouseClicked

    private void ButtonCari2_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCari2_Kelompok2ActionPerformed
      String key=TextFieldCari2_Kelompok2.getText();
        System.out.println(key);

        if(key!=""){
            FindDataKK(key);
        }else{
            LoadTableKK();
        }
    }//GEN-LAST:event_ButtonCari2_Kelompok2ActionPerformed

    private void ButtonBersih_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBersih_Kelompok2ActionPerformed
    bersih();
    }//GEN-LAST:event_ButtonBersih_Kelompok2ActionPerformed

    public final void LoadTable() {
        DefaultTableModel model = new DefaultTableModel();
        TabelWargaRT04_Kelompok2.setModel(model);
        model.addColumn("No KK");
        model.addColumn("NIK");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Umur");
        model.addColumn("Status Hubungan");
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection c = Koneksi.configDB();
            Statement s = c.createStatement();

            String sql = "SELECT * FROM warga_rt04";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                Object[] o = new Object[6];
                o[0] = r.getString("NoKK");
                o[1] = r.getString("NIK");
                o[2] = r.getString("Nama");
                o[3] = r.getString("Jenis_Kelamin");
                o[4] = r.getString("Umur");
                o[5] = r.getString("Status_Hubungan");
               
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terdapat Kesalahan, Harap Periksa Lagi Program/Kodingannya");
        }
    }
    
    private void FindData(String key){
        try{
            DefaultTableModel model = new DefaultTableModel();
            Object[] judul_kolom = {"NoKK", "NIK", "Nama", "Jenis Kelamin", "Umur", "Status Hubungan"};
            model=new DefaultTableModel(null,judul_kolom);
            TabelWargaRT04_Kelompok2.setModel(model);
            
            Connection conn=(Connection)Koneksi.configDB();
            Statement stt=conn.createStatement();
            model.getDataVector().removeAllElements();
            
            String sql = ("SELECT * from warga_rt04 WHERE NoKK LIKE '%"+key+"%' OR NIK LIKE '%"+key+"%' OR Nama LIKE '%"+key+"%'");  
            ResultSet rs = stt.executeQuery(sql);
            while(rs.next()){
                Object[] data={
                    rs.getString("NoKK"),
                    rs.getString("NIK"),
                    rs.getString("Nama"),
                    rs.getString("Jenis_Kelamin"),
                    rs.getString("Umur"),
                    rs.getString("Status_Hubungan")         
                };
               model.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }
    
    private void FindDataKK(String key){
        try{
            DefaultTableModel model = new DefaultTableModel();
            Object[] judul_kolom = {"NoKK", "Kepala Keluarga"};
            model=new DefaultTableModel(null,judul_kolom);
            TabelKeluargaRT04_Kelompok2.setModel(model);
            
            Connection conn=(Connection)Koneksi.configDB();
            Statement stt=conn.createStatement();
            model.getDataVector().removeAllElements();
            
            String sql = ("SELECT * from keluarga_rt04 WHERE NoKK LIKE '%"+key+"%' OR Kepala_Keluarga LIKE '%"+key+"%'");  
            ResultSet rs = stt.executeQuery(sql);
            while(rs.next()){
                Object[] data={
                    rs.getString("NoKK"),
                    rs.getString("Kepala_Keluarga"),
                };
               model.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }

     public final void LoadTableKK() {
        DefaultTableModel model = new DefaultTableModel();
        TabelKeluargaRT04_Kelompok2.setModel(model);
        model.addColumn("No KK");
        model.addColumn("Kepala Keluarga");
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection c = Koneksi.configDB();
            Statement s = c.createStatement();

            String sql = "SELECT * FROM keluarga_rt04";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                Object[] o = new Object[2];
                o[0] = r.getString("NoKK");
                o[1] = r.getString("Kepala_Keluarga");
               
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terdapat Kesalahan, Harap Periksa Lagi Program/Kodingannya");
        }
    }
    
     private void bersih(){
         TextFieldNoKK_Kelompok2.setText("");
         TextFieldNIK_Kelompok2.setText("");
         TextFieldNama_Kelompok2.setText("");
         TextFieldUmur_Kelompok2.setText("");
         ComboBoxStatus_Kelompok2.setSelectedItem("-");
     }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBatal_Kelompok2;
    private javax.swing.JButton ButtonBatal_Kelompok3;
    private javax.swing.JButton ButtonBatal_Kelompok4;
    private javax.swing.JButton ButtonBersih_Kelompok2;
    private javax.swing.JButton ButtonCari2_Kelompok2;
    private javax.swing.JButton ButtonCari_Kelompok2;
    private javax.swing.JButton ButtonCek_Kelompok2;
    private javax.swing.JButton ButtonEdit_Kelompok2;
    private javax.swing.ButtonGroup ButtonGroup_Kelompok2;
    private javax.swing.JButton ButtonInputNIK_Kelompok2;
    private javax.swing.JButton ButtonNIK_Kelompok2;
    private javax.swing.JButton ButtonSimpan_Kelompok2;
    private javax.swing.JButton ButtonTutup_Kelompok2;
    private javax.swing.JComboBox<String> ComboBoxStatus_Kelompok2;
    private javax.swing.JFrame InputData_Kelompok2;
    private javax.swing.JLabel Kelompok2_LabelJudulInput1;
    private javax.swing.JLabel LabelJK_Kelompok2;
    private javax.swing.JLabel LabelJudul1_Kelompok2;
    private javax.swing.JLabel LabelJudul2_Kelompok2;
    private javax.swing.JLabel LabelJudul_Kelompok2;
    private javax.swing.JLabel LabelLogo1_Kelompok2;
    private javax.swing.JLabel LabelLogo2_Kelompok2;
    private javax.swing.JLabel LabelNIK_Kelompok2;
    private javax.swing.JLabel LabelNama_Kelompok2;
    private javax.swing.JLabel LabelNoKK_Kelompok2;
    private javax.swing.JLabel LabelStatus_Kelompok2;
    private javax.swing.JLabel LabelUmur_Kelompok2;
    private javax.swing.JPanel PanelHeader_Kelompok2;
    private javax.swing.JPanel PanelRT04_Kelompok2;
    private javax.swing.JRadioButton RadioLaki_Kelompok2;
    private javax.swing.JRadioButton RadioPerempuan_Kelompok2;
    private javax.swing.JScrollPane ScrollPaneTable_Kelompok2;
    private javax.swing.JScrollPane ScrollPane_Kelompok2;
    private javax.swing.JFrame TabelKK_Kelompok2;
    private javax.swing.JTable TabelKeluargaRT04_Kelompok2;
    private javax.swing.JTable TabelWargaRT04_Kelompok2;
    private javax.swing.JTextField TextFieldCari2_Kelompok2;
    private javax.swing.JTextField TextFieldCari_Kelompok2;
    private javax.swing.JTextField TextFieldNIK_Kelompok2;
    private javax.swing.JTextField TextFieldNama_Kelompok2;
    private javax.swing.JTextField TextFieldNoKK_Kelompok2;
    private javax.swing.JTextField TextFieldUmur_Kelompok2;
    // End of variables declaration//GEN-END:variables
}
