/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bantuan;

import Database.Koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MD
 */
public class Bantuan_RT03 extends javax.swing.JInternalFrame {
 String Bantuan;
 String DateChooser;
    /**
     * Creates new form Bantuan_RT03
     */
    public Bantuan_RT03() {
        initComponents();
        LoadTable();
        LoadTableWarga();
        kode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InputData_Kelompok2 = new javax.swing.JFrame();
        LabelJudul_Kelompok2 = new javax.swing.JLabel();
        LabelNoKK_Kelompok2 = new javax.swing.JLabel();
        LabelNIK_Kelompok2 = new javax.swing.JLabel();
        LabelNama_Kelompok2 = new javax.swing.JLabel();
        LabelBantuan_Kelompok2 = new javax.swing.JLabel();
        LabelJM_Kelompok2 = new javax.swing.JLabel();
        TextFieldNama_Kelompok2 = new javax.swing.JTextField();
        ButtonSimpan_Kelompok2 = new javax.swing.JButton();
        ButtonBatal_Kelompok2 = new javax.swing.JButton();
        TextFieldBantuan_Kelompok2 = new javax.swing.JTextField();
        ButtonEdit_Kelompok2 = new javax.swing.JButton();
        LabelTanggal_Kelompok2 = new javax.swing.JLabel();
        DateChooser_Kelompok2 = new com.toedter.calendar.JDateChooser();
        TextFieldNoKK_Kelompok2 = new javax.swing.JTextField();
        TextFieldNIK_Kelompok2 = new javax.swing.JTextField();
        ButtonCek_Kelompok2 = new javax.swing.JButton();
        jScrollPane_Kelompok2 = new javax.swing.JScrollPane();
        TextAreaKeterangan_Kelompok2 = new javax.swing.JTextArea();
        LabelKode_Kelompok2 = new javax.swing.JLabel();
        TextFieldKode_Kelompok2 = new javax.swing.JTextField();
        ButtonBersih_Kelompok2 = new javax.swing.JButton();
        TabelWarga_Kelompok2 = new javax.swing.JFrame();
        LabelJudul2_Kelompok2 = new javax.swing.JLabel();
        ButtonCari2_Kelompok2 = new javax.swing.JButton();
        TextFieldCari2_Kelompok2 = new javax.swing.JTextField();
        ScrollPaneTable_Kelompok2 = new javax.swing.JScrollPane();
        TabelWargaRT03_Kelompok2 = new javax.swing.JTable();
        PanelHeader_Kelompok2 = new javax.swing.JPanel();
        LabelLogo1_Kelompok2 = new javax.swing.JLabel();
        LabelLogo2_Kelompok2 = new javax.swing.JLabel();
        LabelJudul1_Kelompok2 = new javax.swing.JLabel();
        PanelBantuanRT03_Kelompok2 = new javax.swing.JPanel();
        LabelJudulBantuan_Kelompok2 = new javax.swing.JLabel();
        ScrollPane_Kelompok2 = new javax.swing.JScrollPane();
        TabelBantuanRT03_Kelompok2 = new javax.swing.JTable();
        TextFieldCari_Kelompok2 = new javax.swing.JTextField();
        ButtonCari_Kelompok2 = new javax.swing.JButton();
        ButtonInput_Kelompok2 = new javax.swing.JButton();
        ButtonTutup_Kelompok2 = new javax.swing.JButton();
        ButtonHapus_Kelompok2 = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        PanelHeader_Kelompok3 = new javax.swing.JPanel();
        LabelLogo1_Kelompok3 = new javax.swing.JLabel();
        LabelLogo2_Kelompok3 = new javax.swing.JLabel();
        LabelJudul1_Kelompok3 = new javax.swing.JLabel();
        PanelBantuanRT03_Kelompok3 = new javax.swing.JPanel();
        LabelJudulBantuan_Kelompok3 = new javax.swing.JLabel();
        ScrollPane_Kelompok3 = new javax.swing.JScrollPane();
        TabelBantuanRT03_Kelompok3 = new javax.swing.JTable();
        TextFieldCari_Kelompok3 = new javax.swing.JTextField();
        ButtonCari_Kelompok3 = new javax.swing.JButton();
        ButtonInput_Kelompok3 = new javax.swing.JButton();
        ButtonTutup_Kelompok3 = new javax.swing.JButton();
        ButtonHapus_Kelompok3 = new javax.swing.JButton();

        InputData_Kelompok2.setAlwaysOnTop(true);
        InputData_Kelompok2.setMinimumSize(new java.awt.Dimension(400, 505));

        LabelJudul_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelJudul_Kelompok2.setText("Input Data Bantuan");

        LabelNoKK_Kelompok2.setText("No KK");

        LabelNIK_Kelompok2.setText("NIK");

        LabelNama_Kelompok2.setText("Nama");

        LabelBantuan_Kelompok2.setText("Bantuan");

        LabelJM_Kelompok2.setText("Keterangan");

        TextFieldNama_Kelompok2.setEditable(false);
        TextFieldNama_Kelompok2.setEnabled(false);

        ButtonSimpan_Kelompok2.setText("Simpan");
        ButtonSimpan_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSimpan_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonBatal_Kelompok2.setText("Batal");
        ButtonBatal_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBatal_Kelompok2jButton4ActionPerformed(evt);
            }
        });

        TextFieldBantuan_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldBantuan_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonEdit_Kelompok2.setText("Edit");
        ButtonEdit_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEdit_Kelompok2ActionPerformed(evt);
            }
        });

        LabelTanggal_Kelompok2.setText("Tanggal");

        DateChooser_Kelompok2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                DateChooser_Kelompok2PropertyChange(evt);
            }
        });

        TextFieldNoKK_Kelompok2.setEditable(false);
        TextFieldNoKK_Kelompok2.setEnabled(false);

        TextFieldNIK_Kelompok2.setEditable(false);
        TextFieldNIK_Kelompok2.setEnabled(false);

        ButtonCek_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/find-my-friend - Copy.png"))); // NOI18N
        ButtonCek_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCek_Kelompok2ActionPerformed(evt);
            }
        });

        TextAreaKeterangan_Kelompok2.setColumns(20);
        TextAreaKeterangan_Kelompok2.setRows(5);
        jScrollPane_Kelompok2.setViewportView(TextAreaKeterangan_Kelompok2);

        LabelKode_Kelompok2.setText("Kode");

        TextFieldKode_Kelompok2.setEditable(false);
        TextFieldKode_Kelompok2.setEnabled(false);

        ButtonBersih_Kelompok2.setText("Bersih");
        ButtonBersih_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBersih_Kelompok2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InputData_Kelompok2Layout = new javax.swing.GroupLayout(InputData_Kelompok2.getContentPane());
        InputData_Kelompok2.getContentPane().setLayout(InputData_Kelompok2Layout);
        InputData_Kelompok2Layout.setHorizontalGroup(
            InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputData_Kelompok2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InputData_Kelompok2Layout.createSequentialGroup()
                            .addGroup(InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LabelNoKK_Kelompok2)
                                .addComponent(LabelTanggal_Kelompok2)
                                .addComponent(LabelNIK_Kelompok2)
                                .addComponent(LabelNama_Kelompok2)
                                .addComponent(LabelBantuan_Kelompok2)
                                .addComponent(LabelJM_Kelompok2))
                            .addGap(49, 49, 49)
                            .addGroup(InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(InputData_Kelompok2Layout.createSequentialGroup()
                                    .addComponent(ButtonSimpan_Kelompok2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ButtonBatal_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ButtonBersih_Kelompok2))
                                .addGroup(InputData_Kelompok2Layout.createSequentialGroup()
                                    .addGroup(InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TextFieldNIK_Kelompok2)
                                        .addComponent(TextFieldNoKK_Kelompok2)
                                        .addComponent(DateChooser_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TextFieldNama_Kelompok2)
                                        .addComponent(TextFieldBantuan_Kelompok2)
                                        .addComponent(jScrollPane_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ButtonCek_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(ButtonEdit_Kelompok2)
                                .addComponent(TextFieldKode_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(25, 25, 25))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InputData_Kelompok2Layout.createSequentialGroup()
                            .addComponent(LabelJudul_Kelompok2)
                            .addGap(120, 120, 120)))
                    .addComponent(LabelKode_Kelompok2)))
        );
        InputData_Kelompok2Layout.setVerticalGroup(
            InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputData_Kelompok2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelJudul_Kelompok2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelKode_Kelompok2)
                    .addComponent(TextFieldKode_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateChooser_Kelompok2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTanggal_Kelompok2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldNoKK_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNoKK_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextFieldNIK_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelNIK_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ButtonCek_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNama_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldNama_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldBantuan_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelBantuan_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelJM_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InputData_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSimpan_Kelompok2)
                    .addComponent(ButtonBatal_Kelompok2)
                    .addComponent(ButtonBersih_Kelompok2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonEdit_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TabelWarga_Kelompok2.setAlwaysOnTop(true);
        TabelWarga_Kelompok2.setLocation(new java.awt.Point(361, 5));
        TabelWarga_Kelompok2.setMinimumSize(new java.awt.Dimension(500, 340));

        LabelJudul2_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelJudul2_Kelompok2.setText("Data Warga RT 03");

        ButtonCari2_Kelompok2.setBackground(new java.awt.Color(0, 102, 102));
        ButtonCari2_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonCari2_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCari2_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/find-my-friend.png"))); // NOI18N
        ButtonCari2_Kelompok2.setText("Cari");
        ButtonCari2_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCari2_Kelompok2ActionPerformed(evt);
            }
        });

        TabelWargaRT03_Kelompok2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No KK", "NIK", "Nama", "Jenis Kelamin", "Umur", "Status Hubungan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelWargaRT03_Kelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelWargaRT03_Kelompok2MouseClicked(evt);
            }
        });
        ScrollPaneTable_Kelompok2.setViewportView(TabelWargaRT03_Kelompok2);

        javax.swing.GroupLayout TabelWarga_Kelompok2Layout = new javax.swing.GroupLayout(TabelWarga_Kelompok2.getContentPane());
        TabelWarga_Kelompok2.getContentPane().setLayout(TabelWarga_Kelompok2Layout);
        TabelWarga_Kelompok2Layout.setHorizontalGroup(
            TabelWarga_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelWarga_Kelompok2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TabelWarga_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabelWarga_Kelompok2Layout.createSequentialGroup()
                        .addComponent(LabelJudul2_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonCari2_Kelompok2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextFieldCari2_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ScrollPaneTable_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE))
                .addContainerGap())
        );
        TabelWarga_Kelompok2Layout.setVerticalGroup(
            TabelWarga_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabelWarga_Kelompok2Layout.createSequentialGroup()
                .addGroup(TabelWarga_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFieldCari2_Kelompok2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TabelWarga_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonCari2_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelJudul2_Kelompok2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPaneTable_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelHeader_Kelompok2.setBackground(new java.awt.Color(0, 204, 204));

        LabelLogo1_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Screenshot_20220716-102029_1 - Copy.jpg"))); // NOI18N

        LabelLogo2_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Screenshot_20220716-102029_1 - Copy.jpg"))); // NOI18N

        LabelJudul1_Kelompok2.setBackground(new java.awt.Color(0, 102, 102));
        LabelJudul1_Kelompok2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelJudul1_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        LabelJudul1_Kelompok2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelJudul1_Kelompok2.setText("<html> <center>RT-03</center> </html> ");

        javax.swing.GroupLayout PanelHeader_Kelompok2Layout = new javax.swing.GroupLayout(PanelHeader_Kelompok2);
        PanelHeader_Kelompok2.setLayout(PanelHeader_Kelompok2Layout);
        PanelHeader_Kelompok2Layout.setHorizontalGroup(
            PanelHeader_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelJudul1_Kelompok2)
            .addGroup(PanelHeader_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelHeader_Kelompok2Layout.createSequentialGroup()
                    .addComponent(LabelLogo1_Kelompok2)
                    .addGap(0, 334, Short.MAX_VALUE)))
            .addGroup(PanelHeader_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHeader_Kelompok2Layout.createSequentialGroup()
                    .addGap(0, 334, Short.MAX_VALUE)
                    .addComponent(LabelLogo2_Kelompok2)))
        );
        PanelHeader_Kelompok2Layout.setVerticalGroup(
            PanelHeader_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeader_Kelompok2Layout.createSequentialGroup()
                .addComponent(LabelJudul1_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelHeader_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelHeader_Kelompok2Layout.createSequentialGroup()
                    .addComponent(LabelLogo1_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(PanelHeader_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelHeader_Kelompok2Layout.createSequentialGroup()
                    .addComponent(LabelLogo2_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        PanelBantuanRT03_Kelompok2.setBackground(new java.awt.Color(0, 102, 102));

        LabelJudulBantuan_Kelompok2.setBackground(new java.awt.Color(0, 102, 102));
        LabelJudulBantuan_Kelompok2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LabelJudulBantuan_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        LabelJudulBantuan_Kelompok2.setText("DATA BANTUAN WARGA RT 03");

        TabelBantuanRT03_Kelompok2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Tanggal", "No KK", "NIK", "Nama", "Bantuan", "Keterangan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelBantuanRT03_Kelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelBantuanRT03_Kelompok2MouseClicked(evt);
            }
        });
        ScrollPane_Kelompok2.setViewportView(TabelBantuanRT03_Kelompok2);

        ButtonCari_Kelompok2.setBackground(new java.awt.Color(0, 102, 102));
        ButtonCari_Kelompok2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ButtonCari_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCari_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/find-my-friend.png"))); // NOI18N
        ButtonCari_Kelompok2.setText("Cari");
        ButtonCari_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCari_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonInput_Kelompok2.setBackground(new java.awt.Color(0, 102, 102));
        ButtonInput_Kelompok2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ButtonInput_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonInput_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/input.png"))); // NOI18N
        ButtonInput_Kelompok2.setText("Input Data ");
        ButtonInput_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInput_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonTutup_Kelompok2.setBackground(new java.awt.Color(0, 102, 102));
        ButtonTutup_Kelompok2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ButtonTutup_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonTutup_Kelompok2.setText("TUTUP");
        ButtonTutup_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTutup_Kelompok2ActionPerformed(evt);
            }
        });

        ButtonHapus_Kelompok2.setBackground(new java.awt.Color(0, 102, 102));
        ButtonHapus_Kelompok2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ButtonHapus_Kelompok2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonHapus_Kelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/delete.png"))); // NOI18N
        ButtonHapus_Kelompok2.setText("Hapus Data");
        ButtonHapus_Kelompok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHapus_Kelompok2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBantuanRT03_Kelompok2Layout = new javax.swing.GroupLayout(PanelBantuanRT03_Kelompok2);
        PanelBantuanRT03_Kelompok2.setLayout(PanelBantuanRT03_Kelompok2Layout);
        PanelBantuanRT03_Kelompok2Layout.setHorizontalGroup(
            PanelBantuanRT03_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBantuanRT03_Kelompok2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBantuanRT03_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBantuanRT03_Kelompok2Layout.createSequentialGroup()
                        .addComponent(ScrollPane_Kelompok2)
                        .addContainerGap())
                    .addGroup(PanelBantuanRT03_Kelompok2Layout.createSequentialGroup()
                        .addComponent(LabelJudulBantuan_Kelompok2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonCari_Kelompok2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextFieldCari_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(PanelBantuanRT03_Kelompok2Layout.createSequentialGroup()
                        .addComponent(ButtonInput_Kelompok2)
                        .addGap(263, 263, 263)
                        .addComponent(ButtonTutup_Kelompok2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 303, Short.MAX_VALUE)
                        .addComponent(ButtonHapus_Kelompok2)
                        .addContainerGap())))
        );
        PanelBantuanRT03_Kelompok2Layout.setVerticalGroup(
            PanelBantuanRT03_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBantuanRT03_Kelompok2Layout.createSequentialGroup()
                .addGroup(PanelBantuanRT03_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelJudulBantuan_Kelompok2)
                    .addComponent(ButtonCari_Kelompok2)
                    .addComponent(TextFieldCari_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPane_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelBantuanRT03_Kelompok2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonInput_Kelompok2)
                    .addComponent(ButtonHapus_Kelompok2)
                    .addComponent(ButtonTutup_Kelompok2))
                .addContainerGap())
        );

        PanelHeader_Kelompok3.setBackground(new java.awt.Color(0, 204, 204));

        LabelLogo1_Kelompok3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Screenshot_20220716-102029_1 - Copy.jpg"))); // NOI18N

        LabelLogo2_Kelompok3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Screenshot_20220716-102029_1 - Copy.jpg"))); // NOI18N

        LabelJudul1_Kelompok3.setBackground(new java.awt.Color(0, 102, 102));
        LabelJudul1_Kelompok3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelJudul1_Kelompok3.setForeground(new java.awt.Color(255, 255, 255));
        LabelJudul1_Kelompok3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelJudul1_Kelompok3.setText("<html> <center>RT-03</center> </html> ");

        javax.swing.GroupLayout PanelHeader_Kelompok3Layout = new javax.swing.GroupLayout(PanelHeader_Kelompok3);
        PanelHeader_Kelompok3.setLayout(PanelHeader_Kelompok3Layout);
        PanelHeader_Kelompok3Layout.setHorizontalGroup(
            PanelHeader_Kelompok3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelJudul1_Kelompok3)
            .addGroup(PanelHeader_Kelompok3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelHeader_Kelompok3Layout.createSequentialGroup()
                    .addComponent(LabelLogo1_Kelompok3)
                    .addGap(0, 334, Short.MAX_VALUE)))
            .addGroup(PanelHeader_Kelompok3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHeader_Kelompok3Layout.createSequentialGroup()
                    .addGap(0, 334, Short.MAX_VALUE)
                    .addComponent(LabelLogo2_Kelompok3)))
        );
        PanelHeader_Kelompok3Layout.setVerticalGroup(
            PanelHeader_Kelompok3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeader_Kelompok3Layout.createSequentialGroup()
                .addComponent(LabelJudul1_Kelompok3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelHeader_Kelompok3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelHeader_Kelompok3Layout.createSequentialGroup()
                    .addComponent(LabelLogo1_Kelompok3, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(PanelHeader_Kelompok3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelHeader_Kelompok3Layout.createSequentialGroup()
                    .addComponent(LabelLogo2_Kelompok3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        PanelBantuanRT03_Kelompok3.setBackground(new java.awt.Color(0, 102, 102));

        LabelJudulBantuan_Kelompok3.setBackground(new java.awt.Color(0, 102, 102));
        LabelJudulBantuan_Kelompok3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LabelJudulBantuan_Kelompok3.setForeground(new java.awt.Color(255, 255, 255));
        LabelJudulBantuan_Kelompok3.setText("DATA BANTUAN WARGA RT 03");

        TabelBantuanRT03_Kelompok3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Tanggal", "No KK", "NIK", "Nama", "Bantuan", "Keterangan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelBantuanRT03_Kelompok3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelBantuanRT03_Kelompok3MouseClicked(evt);
            }
        });
        ScrollPane_Kelompok3.setViewportView(TabelBantuanRT03_Kelompok3);

        ButtonCari_Kelompok3.setBackground(new java.awt.Color(0, 102, 102));
        ButtonCari_Kelompok3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ButtonCari_Kelompok3.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCari_Kelompok3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/find-my-friend.png"))); // NOI18N
        ButtonCari_Kelompok3.setText("Cari");
        ButtonCari_Kelompok3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCari_Kelompok3ActionPerformed(evt);
            }
        });

        ButtonInput_Kelompok3.setBackground(new java.awt.Color(0, 102, 102));
        ButtonInput_Kelompok3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ButtonInput_Kelompok3.setForeground(new java.awt.Color(255, 255, 255));
        ButtonInput_Kelompok3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/input.png"))); // NOI18N
        ButtonInput_Kelompok3.setText("Input Data ");
        ButtonInput_Kelompok3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInput_Kelompok3ActionPerformed(evt);
            }
        });

        ButtonTutup_Kelompok3.setBackground(new java.awt.Color(0, 102, 102));
        ButtonTutup_Kelompok3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ButtonTutup_Kelompok3.setForeground(new java.awt.Color(255, 255, 255));
        ButtonTutup_Kelompok3.setText("TUTUP");
        ButtonTutup_Kelompok3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTutup_Kelompok3ActionPerformed(evt);
            }
        });

        ButtonHapus_Kelompok3.setBackground(new java.awt.Color(0, 102, 102));
        ButtonHapus_Kelompok3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ButtonHapus_Kelompok3.setForeground(new java.awt.Color(255, 255, 255));
        ButtonHapus_Kelompok3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/delete.png"))); // NOI18N
        ButtonHapus_Kelompok3.setText("Hapus Data");
        ButtonHapus_Kelompok3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHapus_Kelompok3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBantuanRT03_Kelompok3Layout = new javax.swing.GroupLayout(PanelBantuanRT03_Kelompok3);
        PanelBantuanRT03_Kelompok3.setLayout(PanelBantuanRT03_Kelompok3Layout);
        PanelBantuanRT03_Kelompok3Layout.setHorizontalGroup(
            PanelBantuanRT03_Kelompok3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBantuanRT03_Kelompok3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBantuanRT03_Kelompok3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBantuanRT03_Kelompok3Layout.createSequentialGroup()
                        .addComponent(ScrollPane_Kelompok3)
                        .addContainerGap())
                    .addGroup(PanelBantuanRT03_Kelompok3Layout.createSequentialGroup()
                        .addComponent(LabelJudulBantuan_Kelompok3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonCari_Kelompok3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextFieldCari_Kelompok3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(PanelBantuanRT03_Kelompok3Layout.createSequentialGroup()
                        .addComponent(ButtonInput_Kelompok3)
                        .addGap(263, 263, 263)
                        .addComponent(ButtonTutup_Kelompok3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonHapus_Kelompok3)
                        .addContainerGap())))
        );
        PanelBantuanRT03_Kelompok3Layout.setVerticalGroup(
            PanelBantuanRT03_Kelompok3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBantuanRT03_Kelompok3Layout.createSequentialGroup()
                .addGroup(PanelBantuanRT03_Kelompok3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelJudulBantuan_Kelompok3)
                    .addComponent(ButtonCari_Kelompok3)
                    .addComponent(TextFieldCari_Kelompok3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPane_Kelompok3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelBantuanRT03_Kelompok3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonInput_Kelompok3)
                    .addComponent(ButtonHapus_Kelompok3)
                    .addComponent(ButtonTutup_Kelompok3))
                .addContainerGap())
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelHeader_Kelompok3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelBantuanRT03_Kelompok3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(PanelHeader_Kelompok3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelBantuanRT03_Kelompok3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelHeader_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelBantuanRT03_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelHeader_Kelompok2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelBantuanRT03_Kelompok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabelBantuanRT03_Kelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelBantuanRT03_Kelompok2MouseClicked
        int baris = TabelBantuanRT03_Kelompok2.rowAtPoint(evt.getPoint());
        String Kode =TabelBantuanRT03_Kelompok2.getValueAt(baris, 0).toString();
        TextFieldKode_Kelompok2.setText(Kode);
        String NoKK =TabelBantuanRT03_Kelompok2.getValueAt(baris, 2).toString();
        TextFieldNoKK_Kelompok2.setText(NoKK);
        String NIK = TabelBantuanRT03_Kelompok2.getValueAt(baris,3).toString();
        TextFieldNIK_Kelompok2.setText(NIK);
        String Nama=TabelBantuanRT03_Kelompok2.getValueAt(baris, 4).toString();
        TextFieldNama_Kelompok2.setText(Nama);
        String Bantuan=TabelBantuanRT03_Kelompok2.getValueAt(baris, 5).toString();
        TextFieldBantuan_Kelompok2.setText(Bantuan);
        String Keterangan=TabelBantuanRT03_Kelompok2.getValueAt(baris, 6).toString();
        TextAreaKeterangan_Kelompok2.setText(Keterangan);
    }//GEN-LAST:event_TabelBantuanRT03_Kelompok2MouseClicked

    private void ButtonCari_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCari_Kelompok2ActionPerformed
        String key=TextFieldCari_Kelompok2.getText();
        System.out.println(key);

        if(key!=""){
            FindData(key);
        }else{
            LoadTable();
        }
    }//GEN-LAST:event_ButtonCari_Kelompok2ActionPerformed

    private void ButtonInput_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInput_Kelompok2ActionPerformed
        InputData_Kelompok2.setVisible(true);
    }//GEN-LAST:event_ButtonInput_Kelompok2ActionPerformed

    private void ButtonTutup_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTutup_Kelompok2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_ButtonTutup_Kelompok2ActionPerformed

    private void ButtonHapus_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapus_Kelompok2ActionPerformed
        try {
            String sql ="delete from bantuan_rt03 where Kode='"+TextFieldKode_Kelompok2.getText()+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Data Dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        LoadTable();
        bersih();
    }//GEN-LAST:event_ButtonHapus_Kelompok2ActionPerformed

    private void ButtonCari2_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCari2_Kelompok2ActionPerformed
        String key=TextFieldCari2_Kelompok2.getText();
        System.out.println(key);

        if(key!=""){
            FindDataWarga(key);
        }else{
            LoadTableWarga();
        }
    }//GEN-LAST:event_ButtonCari2_Kelompok2ActionPerformed

    private void TabelWargaRT03_Kelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelWargaRT03_Kelompok2MouseClicked
        int baris = TabelWargaRT03_Kelompok2.rowAtPoint(evt.getPoint());
        String NoKK =TabelWargaRT03_Kelompok2.getValueAt(baris, 0).toString();
        TextFieldNoKK_Kelompok2.setText(NoKK);
        String NIK = TabelWargaRT03_Kelompok2.getValueAt(baris,1).toString();
        TextFieldNIK_Kelompok2.setText(NIK);
        String Nama = TabelWargaRT03_Kelompok2.getValueAt(baris,2).toString();
        TextFieldNama_Kelompok2.setText(Nama);
    }//GEN-LAST:event_TabelWargaRT03_Kelompok2MouseClicked

    private void ButtonSimpan_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSimpan_Kelompok2ActionPerformed
    try {
            String sql = "INSERT INTO bantuan_rt03 VALUES ('"+TextFieldKode_Kelompok2.getText()+"','"
                    +DateChooser+"','"
                    +TextFieldNoKK_Kelompok2.getText()+"','"
                    +TextFieldNIK_Kelompok2.getText()+"','"
                    +TextFieldNama_Kelompok2.getText()+"','"
                    +TextFieldBantuan_Kelompok2.getText()+"','"
                    +TextAreaKeterangan_Kelompok2.getText()+"')";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil DiSimpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    LoadTable();
    kode();
    bersih();
    }//GEN-LAST:event_ButtonSimpan_Kelompok2ActionPerformed

    private void ButtonBatal_Kelompok2jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBatal_Kelompok2jButton4ActionPerformed
    InputData_Kelompok2.dispose();
    }//GEN-LAST:event_ButtonBatal_Kelompok2jButton4ActionPerformed

    private void TextFieldBantuan_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldBantuan_Kelompok2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldBantuan_Kelompok2ActionPerformed

    private void ButtonEdit_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEdit_Kelompok2ActionPerformed
    try {
            String sql ="UPDATE bantuan_rt03 SET Kode = '"+TextFieldKode_Kelompok2.getText()+
                    "',Tanggal = '"+DateChooser+
                    "',NoKK = '"+TextFieldNoKK_Kelompok2.getText()+
                    "',NIK = '"+TextFieldNIK_Kelompok2.getText()+
                    "',Nama= '"+TextFieldNama_Kelompok2.getText()+
                    "',Bantuan= '"+TextFieldBantuan_Kelompok2.getText()+
                    "',Keterangan= '"+TextAreaKeterangan_Kelompok2.getText()+
                    "' WHERE Kode = '"+TextFieldKode_Kelompok2.getText()+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Diedit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Edit Data Gagal!!!"+e.getMessage());
        }
    LoadTable();
    bersih();
    }//GEN-LAST:event_ButtonEdit_Kelompok2ActionPerformed

    private void ButtonCek_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCek_Kelompok2ActionPerformed
    TabelWarga_Kelompok2.setVisible(true);
    }//GEN-LAST:event_ButtonCek_Kelompok2ActionPerformed

    private void DateChooser_Kelompok2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DateChooser_Kelompok2PropertyChange
    try {
        if(DateChooser_Kelompok2.getDate() != null) {
            String pattern = "yyyy-MM-dd";
            SimpleDateFormat format = new SimpleDateFormat(pattern);
            DateChooser=String.valueOf(format.format(DateChooser_Kelompok2.getDate()));
        }
    }catch(Exception e){
        
    }
    }//GEN-LAST:event_DateChooser_Kelompok2PropertyChange

    private void ButtonBersih_Kelompok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBersih_Kelompok2ActionPerformed
    bersih();
    }//GEN-LAST:event_ButtonBersih_Kelompok2ActionPerformed

    private void TabelBantuanRT03_Kelompok3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelBantuanRT03_Kelompok3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TabelBantuanRT03_Kelompok3MouseClicked

    private void ButtonCari_Kelompok3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCari_Kelompok3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCari_Kelompok3ActionPerformed

    private void ButtonInput_Kelompok3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInput_Kelompok3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonInput_Kelompok3ActionPerformed

    private void ButtonTutup_Kelompok3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTutup_Kelompok3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonTutup_Kelompok3ActionPerformed

    private void ButtonHapus_Kelompok3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapus_Kelompok3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonHapus_Kelompok3ActionPerformed

    public final void LoadTable() {
        DefaultTableModel model = new DefaultTableModel();
        TabelBantuanRT03_Kelompok2.setModel(model);
        model.addColumn("Kode");
        model.addColumn("Tanggal");
        model.addColumn("No KK");
        model.addColumn("NIK");
        model.addColumn("Nama");
        model.addColumn("Bantuan");
        model.addColumn("Keterangan");
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection c = Koneksi.configDB();
            Statement s = c.createStatement();

            String sql = "SELECT * FROM bantuan_rt03";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                Object[] o = new Object[7];
                o[0] = r.getString("Kode");
                o[1] = r.getDate("Tanggal");
                o[2] = r.getString("NoKK");
                o[3] = r.getString("NIK");
                o[4] = r.getString("Nama");
                o[5] = r.getString("Bantuan");
                o[6] = r.getString("Keterangan");
               
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terdapat Kesalahan, Harap Periksa Lagi Program/Kodingannya");
        }
    }
    
    public final void LoadTableWarga() {
        DefaultTableModel model = new DefaultTableModel();
        TabelWargaRT03_Kelompok2.setModel(model);
        model.addColumn("No KK");
        model.addColumn("NIK");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Umur");
        model.addColumn("Status Hubungan");
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection c = Koneksi.configDB();
            Statement s = c.createStatement();

            String sql = "SELECT * FROM warga_rt03";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                Object[] o = new Object[6];
                o[0] = r.getString("NoKK");
                o[1] = r.getString("NIK");
                o[2] = r.getString("Nama");
                o[3] = r.getString("Jenis_Kelamin");
                o[4] = r.getString("Umur");
                o[5] = r.getString("Status_Hubungan");
               
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terdapat Kesalahan, Harap Periksa Lagi Program/Kodingannya");
        }
    }
  
    private void FindData(String key){
        try{
            DefaultTableModel model = new DefaultTableModel();
            Object[] judul_kolom = {"Kode","Tanggal","NoKK", "NIK", "Nama", "Bantuan", "Keterangan"};
            model=new DefaultTableModel(null,judul_kolom);
            TabelBantuanRT03_Kelompok2.setModel(model);
            
            Connection conn=(Connection)Koneksi.configDB();
            Statement stt=conn.createStatement();
            model.getDataVector().removeAllElements();
            
            String sql = ("SELECT * from bantuan_rt03 WHERE Kode LIKE '%"+key+"%' OR Tanggal LIKE '%"+key+"%' OR NoKK LIKE '%"+key+"%' OR NIK LIKE '%"+key+"%' OR Nama LIKE '%"+key+"%' OR Bantuan LIKE '%"+key+"%' OR Keterangan LIKE '%"+key+"%'");  
            ResultSet rs = stt.executeQuery(sql);
            while(rs.next()){
                Object[] data={
                    rs.getString("Kode"),
                    rs.getDate("Tanggal"),
                    rs.getString("NoKK"),
                    rs.getString("NIK"),
                    rs.getString("Nama"),
                    rs.getString("Bantuan"),
                    rs.getString("Keterangan"),
                };
               model.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }
    
    private void FindDataWarga(String key){
        try{
            DefaultTableModel model = new DefaultTableModel();
            Object[] judul_kolom = {"NoKK", "NIK", "Nama", "Jenis Kelamin", "Umur", "Status Hubungan"};
            model=new DefaultTableModel(null,judul_kolom);
            TabelWargaRT03_Kelompok2.setModel(model);
            
            Connection conn=(Connection)Koneksi.configDB();
            Statement stt=conn.createStatement();
            model.getDataVector().removeAllElements();
            
            String sql = ("SELECT * from warga_rt03 WHERE NoKK LIKE '%"+key+"%' OR NIK LIKE '%"+key+"%' OR Nama LIKE '%"+key+"%'");  
            ResultSet rs = stt.executeQuery(sql);
            while(rs.next()){
                Object[] data={
                    rs.getString("NoKK"),
                    rs.getString("NIK"),
                    rs.getString("Nama"),
                    rs.getString("Jenis_Kelamin"),
                    rs.getString("Umur"),
                    rs.getString("Status_Hubungan")         
                };
               model.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }
    
    private void kode()
    {
       try {
            Connection conn=(Connection)Koneksi.configDB();
            Statement stt=conn.createStatement();
            String sql="select * from bantuan_rt03 order by Kode desc";
            ResultSet rs = stt.executeQuery(sql);
            if (rs.next()) {
                String kode = rs.getString("Kode").substring(3);
                String BAN = "" + (Integer.parseInt(kode) + 1);
                String Nol = "";

                if(BAN.length()==1)
                {Nol = "000";}
                else if(BAN.length()==2)
                {Nol = "00";}
                else if(BAN.length()==3)
                {Nol = "0";}
                else if(BAN.length()==4)
                {Nol = "";}

               TextFieldKode_Kelompok2.setText("BAN" + Nol + BAN);
            } else {
               TextFieldKode_Kelompok2.setText("BAN0001");
            }

           }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }
     }
    
    private void bersih(){
        TextFieldNoKK_Kelompok2.setText("");
        TextFieldNIK_Kelompok2.setText("");
        TextFieldNama_Kelompok2.setText("");
        TextFieldBantuan_Kelompok2.setText("");
        TextAreaKeterangan_Kelompok2.setText("");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBatal_Kelompok2;
    private javax.swing.JButton ButtonBersih_Kelompok2;
    private javax.swing.JButton ButtonCari2_Kelompok2;
    private javax.swing.JButton ButtonCari_Kelompok2;
    private javax.swing.JButton ButtonCari_Kelompok3;
    private javax.swing.JButton ButtonCek_Kelompok2;
    private javax.swing.JButton ButtonEdit_Kelompok2;
    private javax.swing.JButton ButtonHapus_Kelompok2;
    private javax.swing.JButton ButtonHapus_Kelompok3;
    private javax.swing.JButton ButtonInput_Kelompok2;
    private javax.swing.JButton ButtonInput_Kelompok3;
    private javax.swing.JButton ButtonSimpan_Kelompok2;
    private javax.swing.JButton ButtonTutup_Kelompok2;
    private javax.swing.JButton ButtonTutup_Kelompok3;
    private com.toedter.calendar.JDateChooser DateChooser_Kelompok2;
    private javax.swing.JFrame InputData_Kelompok2;
    private javax.swing.JLabel LabelBantuan_Kelompok2;
    private javax.swing.JLabel LabelJM_Kelompok2;
    private javax.swing.JLabel LabelJudul1_Kelompok2;
    private javax.swing.JLabel LabelJudul1_Kelompok3;
    private javax.swing.JLabel LabelJudul2_Kelompok2;
    private javax.swing.JLabel LabelJudulBantuan_Kelompok2;
    private javax.swing.JLabel LabelJudulBantuan_Kelompok3;
    private javax.swing.JLabel LabelJudul_Kelompok2;
    private javax.swing.JLabel LabelKode_Kelompok2;
    private javax.swing.JLabel LabelLogo1_Kelompok2;
    private javax.swing.JLabel LabelLogo1_Kelompok3;
    private javax.swing.JLabel LabelLogo2_Kelompok2;
    private javax.swing.JLabel LabelLogo2_Kelompok3;
    private javax.swing.JLabel LabelNIK_Kelompok2;
    private javax.swing.JLabel LabelNama_Kelompok2;
    private javax.swing.JLabel LabelNoKK_Kelompok2;
    private javax.swing.JLabel LabelTanggal_Kelompok2;
    private javax.swing.JPanel PanelBantuanRT03_Kelompok2;
    private javax.swing.JPanel PanelBantuanRT03_Kelompok3;
    private javax.swing.JPanel PanelHeader_Kelompok2;
    private javax.swing.JPanel PanelHeader_Kelompok3;
    private javax.swing.JScrollPane ScrollPaneTable_Kelompok2;
    private javax.swing.JScrollPane ScrollPane_Kelompok2;
    private javax.swing.JScrollPane ScrollPane_Kelompok3;
    private javax.swing.JTable TabelBantuanRT03_Kelompok2;
    private javax.swing.JTable TabelBantuanRT03_Kelompok3;
    private javax.swing.JTable TabelWargaRT03_Kelompok2;
    private javax.swing.JFrame TabelWarga_Kelompok2;
    private javax.swing.JTextArea TextAreaKeterangan_Kelompok2;
    private javax.swing.JTextField TextFieldBantuan_Kelompok2;
    private javax.swing.JTextField TextFieldCari2_Kelompok2;
    private javax.swing.JTextField TextFieldCari_Kelompok2;
    private javax.swing.JTextField TextFieldCari_Kelompok3;
    private javax.swing.JTextField TextFieldKode_Kelompok2;
    private javax.swing.JTextField TextFieldNIK_Kelompok2;
    private javax.swing.JTextField TextFieldNama_Kelompok2;
    private javax.swing.JTextField TextFieldNoKK_Kelompok2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JScrollPane jScrollPane_Kelompok2;
    // End of variables declaration//GEN-END:variables
}
